var data = [
  ["Gand", "[ɡɑ̃]", "根特（比利时城市）", "Gand est une belle ville en Belgique   (根特是比利时的一座美丽城市。)"],
  ["garçon", "[ɡaʁsɔ̃]", "男孩，男服务员", "Le garçon a apporté les menus   (服务员拿来了菜单。)"],
  ["garçons", "[ɡaʁsɔ̃]", "男孩们，男服务员们", "Les garçons jouent au football   (男孩们在踢足球。)"],
  ["gare", "[ɡɑʁ]", "火车站", "La gare est loin d'ici   (火车站离这里很远。)"],
  ["gares", "[ɡɑʁ]", "火车站们", "Il y a plusieurs gares dans la ville   (这座城市有好几个火车站。)"],
  ["gâteau", "[ɡɑto]", "蛋糕", "J'ai préparé un gâteau au chocolat   (我做了一个巧克力蛋糕。)"],
  ["gâteaux", "[ɡɑto]", "蛋糕们", "Les gâteaux sont délicieux   (蛋糕们非常美味。)"],
  ["gauche", "[ɡoʃ]", "左边，左的", "La porte est à gauche   (门在左边。)"],
  ["gauches", "[ɡoʃ]", "左边的（复数）", "Les gauches côtés sont occupés   (左边的座位被占用了。)"],
  ["gazeuse", "[ɡazøz]", "含气的，气泡的", "L'eau gazeuse est rafraîchissante   (气泡水很提神。)"],
  ["génial", "[ʒe  njal]", "很棒的，极好的", "Ce film est génial ! (这部电影太棒了！)"],
  ["géniales", "[ʒe  njal]", "很棒的（女性复数）", "Les idées géniales viennent souvent d’un esprit créatif  创造头脑"],
  ["géniaux", "[ʒe  njal]", "很棒的（男性复数）", "Les films géniaux peuvent être très simples  很棒的电影可以简单"],
  ["genre", "[ʒɑ̃ʁ]", "种类，类型", "Quel genre de musique préfères-tu ? (你喜欢什么类型的音乐？)"],
  ["gens", "[ʒɑ̃]", "人们", "Les gens sont très amicaux ici   (这里的人们非常友好。)"],
  ["gentil", "[ʒɑ̃  til]", "和善的，友好的", "Il est très gentil avec tout le monde   (他对每个人都很友好。)"],
  ["gentille", "[ʒɑ̃  tij]", "和善的（女性）", "Elle est gentille avec les enfants   (她对孩子们很友善。)"],
  ["gentilles", "[ʒɑ̃  tij]", "和善的（女性复数）", "Elles sont toutes gentilles   (她们都很友善。)"],
  ["gentils", "[ʒɑ̃  til]", "和善的（男性复数）", "Les garçons sont gentils   (男孩们很友善。)"],
  ["géographie", "[ʒe  ɔɡʁa  fi]", "地理学", "La géographie est une matière importante à l'école   (地理学是学校里的重要学科。)"],
  ["grâce", "[ɡʁas]", "感谢，恩典", "Il a réussi grâce à son travail acharné   (他凭借辛勤的工作成功了。)"],
  ["grammaire", "[ɡʁa  mɛʁ]", "语法", "La grammaire française est compliquée   (法语语法很复杂。)"],
  ["grand", "[ɡʁɑ̃]", "大的，伟大的", "Il est un grand joueur de tennis   (他是一个伟大的网球选手。)"],
  ["grand frère", "[ɡʁɑ̃ fʁɛʁ]", "大哥哥", "Mon grand frère joue au football   (我的大哥哥踢足球。)"],
  ["grand-mère", "[ɡʁɑ̃ mɛʁ]", "外祖母，祖母", "Ma grand-mère adore faire du jardinage   (我的祖母喜欢园艺。)"],
  ["grand-père", "[ɡʁɑ̃ pɛʁ]", "外祖父，祖父", "Mon grand-père est très sage   (我的祖父非常睿智。)"],
  ["grande", "[ɡʁɑ̃d]", "大的（女性）", "Elle a une grande maison   (她有一栋大房子。)"],
  ["grande sœur", "[ɡʁɑ̃d sœʁ]", "大姐姐", "Ma grande sœur est médecin   (我的大姐姐是医生。)"],
  ["grandes", "[ɡʁɑ̃d]", "大的（女性复数）", "Elles ont de grandes idées   (她们有很棒的主意。)"],
  ["grands", "[ɡʁɑ̃]", "大的（男性复数）", "Les grands arbres sont majestueux   (大树雄伟壮丽。)"],
  ["grands-parents", "[ɡʁɑ̃ pɑʁɑ̃]", "祖父母，外祖父母", "Mes grands-parents habitent à la campagne   我的祖父母住在乡下"],
  ["gris", "[ɡʁi]", "灰色的", "Le ciel est gris aujourd'hui   (今天天空是灰色的。)"],
  ["gros", "[ɡʁo]", "大的，胖的", "Il est gros mais gentil   (他很胖，但很友好。)"],
  ["groupe", "[ɡʁup]", "团体，小组", "Nous avons formé un groupe pour le projet   (我们为这个项目组成了一个小组。)"],
  ["guide", "[ɡid]", "导游，指南", "Le guide nous a montré la ville   (导游带我们参观了城市。)"],
  ["guides", "[ɡid]", "导游们，指南们", "Les guides touristiques expliquent l’histoire   (旅游指南讲解历史。)"],
  ["guitare", "[ɡi  taʁ]", "吉他", "Il joue de la guitare tous les jours   (他每天弹吉他。)"],
];