var data = [
  ["habille", "[a  bij]", "穿衣服", "Je m'habille rapidement   (我迅速穿好衣服。)"],
  ["habilles", "[a  bij]", "穿衣服（你）", "Tu habilles bien   (你穿得很合适。)"],
  ["habitais", "[a  bi  tɛ]", "住（你过去）", "Quand j'étais jeune, j'habitais à Paris   (我小时候住在巴黎。)"],
  ["habite", "[a  bit]", "住（我/他）", "Elle habite en France   (她住在法国。)"],
  ["habitent", "[a  bjɛt]", "住（他们）", "Ils habitent à Londres   (他们住在伦敦。)"],
  ["habiter", "[a  bi  te]", "住", "Nous habitons ici depuis cinq ans   (我们已经在这里住了五年。)"],
  ["habites", "[a  bit]", "住（你）", "Où habites-tu ? (你住在哪儿？)"],
  ["habitez", "[a  bi  te]", "住（您/你们）", "Vous habitez à Paris ? (你们住在巴黎吗？)"],
  ["habitons", "[a  bi  tɔ̃]", "住（我们）", "Nous habitons près de l'école   (我们住在学校附近。)"],
  ["haut", "[o]", "高的，向上", "Il parle d'une voix haute   (他说话声音很大。)"],
  ["heures", "[œʁ]", "小时，点（钟）", "Il est trois heures   (现在是三点钟。)"],
  ["heureux", "[øʁø]", "幸福的", "Il est très heureux   (他非常幸福。)"],
  ["hier", "[jɛʁ]", "昨天", "Hier, j'ai visité un musée   (昨天我参观了一个博物馆。)"],
  ["histoire", "[is  twaʁ]", "历史，故事", "L'histoire de ce pays est fascinante   (这个国家的历史很迷人。)"],
  ["hiver", "[ivɛʁ]", "冬天", "L'hiver est froid   (冬天很冷。)"],
  ["homme", "[ɔm]", "男人，人", "C'est un homme gentil   (他是一个很友善的男人。)"],
  ["hommes", "[ɔm]", "男人们，男士们", "Les hommes travaillent ici   (这些男士在这里工作。)"],
  ["hôpital", "[ɔ  pi  tal]", "医院", "L'hôpital est près d'ici   (医院就在附近。)"],
  ["hôpitaux", "[ɔ  pi  to]", "医院们", "Les hôpitaux sont pleins   (医院人满为患。)"],
  ["horloge", "[ɔʁ  lɔʒ]", "时钟", "La horloge est cassée   (时钟坏了。)"],
  ["hôtel", "[o  tɛl]", "酒店", "L'hôtel est à côté de la gare   (酒店就在火车站旁边。)"],
  ["hôtel de ville", "[o  tɛl də vil]", "市政府", "L'hôtel de ville est dans le centre   (市政府在市中心。)"],
  ["hôtels", "[o  tɛl]", "酒店们", "Il y a beaucoup d'hôtels à Paris   (巴黎有很多酒店。)"],
  ["huit", "[ɥit]", "八", "J'ai huit ans   (我八岁。)"],
  ["huitième", "[ɥi  tjɛm]", "第八", "C'est le huitième jour du mois   (今天是这个月的第八天。)"],
];