var data = [
  ["ici", "[i  si]", "这里", "Je suis ici   (我在这里。)"],
  ["idée", "[i  de]", "主意，想法", "J'ai une idée   (我有一个主意。)"],
  ["idées", "[i  de]", "主意们，想法们", "Elles ont des idées intéressantes   (她们有有趣的想法。)"],
  ["il", "[il]", "他，它", "Il est mon ami   (他是我的朋友。)"],
  ["ils", "[il]", "他们，它们", "Ils sont en retard   (他们迟到了。)"],
  ["immédiatement", "[im  me  djɑ  tə  mɑ̃]", "立刻", "Je vais le faire immédiatement   (我会立刻做的。)"],
  ["immeuble", "[i  mœbl]", "建筑物，楼房", "Cet immeuble est très vieux   (这栋楼很旧。)"],
  ["important", "[ɛ̃  pɔʁ  tɑ̃]", "重要的", "C'est un problème important   (这是一个重要的问题。)"],
  ["importante", "[ɛ̃  pɔʁ  tɑ̃t]", "重要的（女性）", "Elle a une opinion importante   (她有一个重要的观点。)"],
  ["indien", "[ɛ̃  djɛ̃]", "印度的，印度人", "Il est d'origine indienne   (他是印度人。)"],
  ["indienne", "[ɛ̃  djɛn]", "印度的（女性）", "Elle porte une robe indienne   (她穿着印度风格的裙子。)"],
  ["informations", "[ɛ̃  fɔʁ  ma  sjɔ̃]", "信息，消息", "Les informations sont sur le site   (信息在网站上。)"],
  ["ingénieurs", "[ɛ̃  ʒe  njœʁ]", "工程师们", "Les ingénieurs travaillent sur le projet   (工程师们正在做这个项目。)"],
  ["inquiète", "[ɛ̃  kjɛt]", "焦虑的（女性）", "Elle est inquiète pour son examen   (她对考试感到焦虑。)"],
  ["inquiètes", "[ɛ̃  kjɛt]", "焦虑的（女性复数）", "Elles sont inquiètes   (她们很焦虑。)"],
  ["inquiets", "[ɛ̃  kjɛt]", "焦虑的（男性）", "Ils sont inquiets à propos de l'avenir   (他们对未来感到焦虑。)"],
  ["intelligent", "[ɛ̃  te  li  ʒɑ̃]", "聪明的", "Il est intelligent   (他很聪明。)"],
  ["intelligente", "[ɛ̃  te  li  ʒɑ̃t]", "聪明的（女性）", "Elle est intelligente   (她很聪明。)"],
  ["intelligentes", "[ɛ̃  te  li  ʒɑ̃t]", "聪明的（女性复数）", "Elles sont intelligentes   (她们很聪明。)"],
  ["intelligents", "[ɛ̃  te  li  ʒɑ̃]", "聪明的（男性复数）", "Ils sont intelligents   (他们很聪明。)"],
  ["interdits", "[ɛ̃  tɛʁ  dɪ]", "被禁止的", "Les accès sont interdits   (这些地方是禁止进入的。)"],
  ["intéressant", "[ɛ̃  te  ʁɛ  sɑ̃]", "有趣的", "Ce film est très intéressant   (这部电影非常有趣。)"],
  ["intéressante", "[ɛ̃  te  ʁɛ  sɑ̃t]", "有趣的（女性）", "L'exposition est intéressante   (展览很有趣。)"],
  ["invite", "[ɛ̃  vit]", "邀请（我/他）", "Je t'invite à ma fête   (我邀请你来我的聚会。)"],
  ["invitent", "[ɛ̃  vit]", "邀请（他们）", "Ils invitent leurs amis   (他们邀请了他们的朋友。)"],
  ["inviter", "[ɛ̃  vi  te]", "邀请", "Il invite ses collègues   (他邀请了他的同事。)"],
  ["invites", "[ɛ̃  vit]", "邀请（你）", "Tu invites des amis ? (你邀请朋友了吗？)"],
  ["Italie", "[i  ta  li]", "意大利", "L'Italie est un beau pays   (意大利是一个美丽的国家。)"],
  ["italien", "[i  ta  ljɛ̃]", "意大利的，意大利人", "Il parle italien   (他说意大利语。)"],
  ["italiennes", "[i  ta  ljɛn]", "意大利的（女性）", "Elles sont italiennes   (她们是意大利人。)"],
  ["italiens", "[i  ta  ljɛ̃]", "意大利的（男性）", "Les italiens aiment la pizza   (意大利人喜欢比萨。)"],
];