var data = [
  ["j'", "[ʒə]", "我（省略形式）", "J'ai un livre   (我有一本书。)"],
  ["jamais", "[ʒa  mɛ]", "从不", "Je ne mange jamais de chocolat   (我从不吃巧克力。)"],
  ["jambe", "[ʒɑ̃b]", "腿", "Elle a mal à la jambe   (她的腿痛。)"],
  ["jambes", "[ʒɑ̃b]", "腿（复数）", "Il a de longues jambes   (他有长腿。)"],
  ["janvier", "[ʒɑ̃  vje]", "一月", "Le mois de janvier est froid   (一月很冷。)"],
  ["Japon", "[ʒa  pɔ̃]", "日本", "Le Japon est un pays en Asie   (日本是一个位于亚洲的国家。)"],
  ["japonais", "[ʒa  pɔ  nɛ]", "日本的，日语", "Il parle japonais   (他说日语。)"],
  ["japonaise", "[ʒa  pɔ  nɛz]", "日本的（女性）", "Elle est japonaise   (她是日本人。)"],
  ["japonaises", "[ʒa  pɔ  nɛz]", "日本的（女性复数）", "Elles sont japonaises   (她们是日本人。)"],
  ["jardin", "[ʒaʁ  dɛ̃]", "花园", "Il travaille dans le jardin   (他在花园里工作。)"],
  ["jaune", "[ʒon]", "黄色的", "La banane est jaune   (香蕉是黄色的。)"],
  ["jaunes", "[ʒon]", "黄色的（复数）", "Les fleurs sont jaunes   (这些花是黄色的。)"],
  ["je", "[ʒə]", "我", "Je mange une pomme   (我吃一个苹果。)"],
  ["jeudi", "[ʒø  di]", "星期四", "Nous avons cours jeudi   (我们星期四上课。)"],
  ["joue", "[ʒu]", "玩（我/他）", "Il joue au tennis   (他打网球。)"],
  ["jouent", "[ʒwɑ̃]", "玩（他们）", "Ils jouent au football   (他们踢足球。)"],
  ["jouer", "[ʒwe]", "玩，游戏", "J'aime jouer aux jeux vidéo   (我喜欢玩电子游戏。)"],
  ["jour", "[ʒuʁ]", "日，天", "Aujourd'hui, c'est un beau jour   (今天是个美好的一天。)"],
  ["journal", "[ʒuʁ  nal]", "日报，杂志", "Je lis un journal chaque matin   (我每天早上读报纸。)"],
  ["journaliste", "[ʒuʁ  nalist]", "记者", "Elle est journaliste   (她是记者。)"],
  ["journalistes", "[ʒuʁ  nalist]", "记者们", "Les journalistes travaillent toute la journée   (记者们工作整天。)"],
  ["journaux", "[ʒuʁ  no]", "报纸（复数）", "Il achète des journaux   (他买报纸。)"],
  ["journée", "[ʒuʁ  ne]", "一天，白天", "La journée a été longue   (这一天很长。)"],
  ["juillet", "[ʒɥi  jɛ]", "七月", "Nous partons en vacances en juillet   (我们七月去度假。)"],
  ["juin", "[ʒwɛ̃]", "六月", "Mon anniversaire est en juin   (我的生日在六月。)"],
  ["jupe", "[ʒyp]", "裙子", "Elle porte une jupe rouge   (她穿着一条红裙子。)"],
  ["jupes", "[ʒyp]", "裙子（复数）", "Les jupes sont jolies   (这些裙子很漂亮。)"],
  ["jus", "[ʒy]", "果汁", "Je bois du jus d'orange   (我喝橙汁。)"],
  ["jusqu'", "[ʒysk]", "直到", "Je travaille jusqu'à cinq heures   (我工作到五点。)"],
  ["jusque", "[ʒysk]", "直到", "Il marche jusque chez moi   (他走到我家。)"],
  ["italiens", "[i  ta  ljɛ̃]", "意大利的（男性）", "Les italiens aiment la pizza   (意大利人喜欢比萨。)"],
];