var data = [
  ["l'", "[l‿]", "（定冠词）", "L'ami de Marie est ici   (玛丽的朋友在这里。)"],
  ["là", "[lɑ]", "那里", "Je vais là-bas   (我去那里。)"],
  ["la", "[la]", "她（阴性主语）", "La voiture est rouge   (那辆车是红色的。)"],
  ["là-bas", "[lɑ‿ba]", "那边，那里", "Les enfants jouent là-bas   (孩子们在那里玩。)"],
  ["lac", "[lak]", "湖", "Le lac est très calme   (湖面非常平静。)"],
  ["lait", "[lɛ]", "牛奶", "Il boit du lait   (他喝牛奶。)"],
  ["langue", "[lɑ̃ɡ]", "语言", "La langue française est belle   (法语很美。)"],
  ["langues", "[lɑ̃ɡ]", "语言（复数）", "Elle parle plusieurs langues   (她说几种语言。)"],
  ["lapins", "[lapɛ̃]", "兔子（复数）", "Les lapins sont mignons   (兔子很可爱。)"],
  ["lave", "[lav]", "洗（我/他）", "Je lave les mains   (我洗手。)"],
  ["laver", "[lavɛʁ]", "洗", "Je vais laver la voiture   (我要洗车。)"],
  ["laves", "[lav]", "洗（你）", "Tu laves les légumes   (你洗蔬菜。)"],
  ["le", "[lə]", "他（阳性主语）", "Le film est intéressant   (电影很有趣。)"],
  ["leçon", "[lə  sɔ̃]", "课", "La leçon est facile   (这节课很简单。)"],
  ["leçons", "[lə  sɔ̃]", "课（复数）", "Les leçons sont difficiles   (这些课很难。)"],
  ["lentement", "[lɑ̃təmɑ̃]", "慢慢地", "Il parle lentement   (他说得很慢。)"],
  ["les", "[le]", "他们（复数）", "Les enfants jouent dehors   (孩子们在外面玩。)"],
  ["leur", "[lœʁ]", "他们的", "C'est leur maison   (这是他们的房子。)"],
  ["leurs", "[lœʁ]", "他们的（复数）", "Ils aiment leurs parents   (他们爱他们的父母。)"],
  ["lève", "[lɛv]", "举起（我/他）", "Il lève la main   (他举手。)"],
  ["lever", "[ləve]", "举起", "Il faut lever la main pour parler   (要举手才能发言。)"],
  ["lèves", "[lɛv]", "举起（你）", "Tu lèves les bras   (你举起手臂。)"],
  ["librairie", "[li  bʁɛʁi]", "书店", "Elle va à la librairie   (她去书店。)"],
  ["lieu", "[ljø]", "地方", "Ce lieu est très calme   (这个地方非常安静。)"],
  ["lieux", "[ljø]", "地方（复数）", "Les lieux sont magnifiques   (这些地方很美。)"],
  ["limonade", "[li  mɔ  nad]", "柠檬水", "Je bois de la limonade   (我喝柠檬水。)"],
  ["lire", "[liʁ]", "阅读", "Il aime lire des livres   (他喜欢读书。)"],
  ["lis", "[li]", "阅读（我/你）", "Je lis un roman   (我读一本小说。)"],
  ["lisez", "[li  ze]", "阅读（你们）", "Vous lisez le livre   (你们在读书。)"],
  ["lit", "[li]", "床", "Il dort dans son lit   (他在床上睡觉。)"],
  ["lits", "[li]", "床（复数）", "Les lits sont confortables   (这些床很舒服。)"],
  ["livre", "[livʁ]", "书", "Le livre est sur la table   (书在桌子上。)"],
  ["livres", "[livʁ]", "书（复数）", "Les livres sont intéressants   (这些书很有趣。)"],
  ["loin", "[lwɛ̃]", "远", "La maison est loin d'ici   (房子离这里很远。)"],
  ["Loire", "[lwaʁ]", "卢瓦尔河", "La Loire traverse la France   (卢瓦尔河穿过法国。)"],
  ["Londres", "[lɔ̃dʁ]", "伦敦", "Nous allons à Londres   (我们去伦敦。)"],
  ["long", "[lɔ̃]", "长", "Il est grand et long   (它又大又长。)"],
  ["longtemps", "[lɔ̃tɑ̃]", "很长时间", "Il a dormi longtemps   (他睡了很长时间。)"],
  ["Louvre", "[luvʁ]", "卢浮宫", "Le Louvre est un musée célèbre   (卢浮宫是一个著名的博物馆。)"],
  ["lui", "[lɥi]", "他（间接宾格）", "Je lui parle   (我在跟他说话。)"],
  ["lundi", "[lœ̃  di]", "星期一", "Nous avons cours lundi   (我们星期一上课。)"],
  ["lunettes", "[ly  nɛt]", "眼镜", "Elle porte des lunettes   (她戴眼镜。)"],
  ["Luxembourg", "[lʏksœ̃buʁɡ]", "卢森堡", "Le Luxembourg est un petit pays   (卢森堡是一个小国家。)"],
  ["lycée", "[li  se]", "高中", "Il étudie au lycée   (他在高中学习。)"],
  ["Lyon", "[ljɔ̃]", "里昂", "Lyon est une grande ville   (里昂是一个大城市。)"],
];