var data = [
  ["m'", "[m‿]", "我（代词，缩写）", "M'appelez-vous quand vous arrivez   (你到达时给我打电话。)"],
  ["m'appelle", "[ma  pɛl]", "叫我（动词）", "Je m'appelle Marie   (我叫玛丽。)"],
  ["ma", "[ma]", "我的（阴性）", "Ma mère est gentille   (我妈妈很友好。)"],
  ["madame", "[ma  dam]", "女士", "Madame Dupont est ici   (Dupont女士在这里。)"],
  ["mademoiselle", "[ma  də  mwa  zɛl]", "小姐", "Mademoiselle Martin travaille à l'école   (Martin小姐在学校工作。)"],
  ["Madrid", "[ma  dʁid]", "马德里", "Nous allons à Madrid   (我们去马德里。)"],
  ["magasin", "[ma  ɡa  zɛ̃]", "商店", "Je vais au magasin   (我去商店。)"],
  ["magasins", "[ma  ɡa  zɛ̃]", "商店（复数）", "Les magasins sont ouverts   (商店开着。)"],
  ["mai", "[mɛ]", "五月", "Le mois de mai est très beau   (五月非常美丽。)"],
  ["main", "[mɛ̃]", "手", "Il me donne sa main   (他把手伸给我。)"],
  ["mains", "[mɛ̃]", "手（复数）", "Mes mains sont propres   (我的手很干净。)"],
  ["maintenant", "[mɛ̃t‿nɑ̃]", "现在", "Il est tard maintenant   (现在很晚了。)"],
  ["mais", "[mɛ]", "但是", "J'aime le chocolat, mais je préfère le café   (我喜欢巧克力，但更喜欢咖啡。)"],
  ["maison", "[mɛ  zɔ̃]", "房子", "La maison est grande   (这房子很大。)"],
  ["maisons", "[mɛ  zɔ̃]", "房子（复数）", "Les maisons sont jolies   (这些房子很漂亮。)"],
  ["mal", "[mal]", "坏，疼，错误", "Ça va mal   (不太好。)"],
  ["malade", "[ma  lad]", "生病的（形容词）", "Elle est malade   (她生病了。)"],
  ["malades", "[ma  lad]", "生病的（复数）", "Les enfants sont malades   (孩子们生病了。)"],
  ["malheureusement", "[malœʁøz‿mɑ̃]", "不幸地", "Malheureusement, il pleut   (不幸的是，下雨了。)"],
  ["maman", "[ma  mɑ̃]", "妈妈", "Ma maman est gentille   (我妈妈很温柔。)"],
  ["mamie", "[ma  mi]", "奶奶", "Mamie m'a offert un cadeau   (奶奶给了我一个礼物。)"],
  ["mange", "[mɑ̃ʒ]", "吃（我/他）", "Je mange une pomme   (我吃一个苹果。)"],
  ["mangent", "[mɑ̃ʒ]", "吃（他们）", "Ils mangent des légumes   (他们吃蔬菜。)"],
  ["mangeons", "[mɑ̃ʒ‿ɔ̃]", "吃（我们）", "Nous mangeons à la maison   (我们在家吃饭。)"],
  ["manger", "[mɑ̃ʒe]", "吃", "Je vais manger   (我要吃饭。)"],
  ["manges", "[mɑ̃ʒ]", "吃（你）", "Tu manges du pain   (你吃面包。)"],
  ["mangez", "[mɑ̃ʒe]", "吃（你们）", "Vous mangez au restaurant   (你们在餐厅吃饭。)"],
  ["Manon", "[ma  nɔ̃]", "玛农（人名）", "Manon est ma sœur   (玛农是我的妹妹。)"],
  ["manteau", "[mɑ̃  to]", "外套", "Il porte un manteau noir   (他穿着一件黑色的外套。)"],
  ["manteaux", "[mɑ̃  to]", "外套（复数）", "Les manteaux sont chers   (这些外套很贵。)"],
  ["manuel", "[ma  nœl]", "手册", "Le manuel est sur la table   (手册在桌子上。)"],
  ["manuels", "[ma  nœl]", "手册（复数）", "Les manuels sont vieux   (这些手册很旧。)"],
  ["marché", "[maʁ  ʃe]", "市场", "Je vais au marché   (我去市场。)"],
  ["marche", "[maʁʃ]", "走（我/他）", "Elle marche vite   (她走得很快。)"],
  ["marcher", "[maʁʃe]", "走", "Nous allons marcher   (我们去走路。)"],
  ["marches", "[maʁʃ]", "走（你）", "Tu marches lentement   (你走得很慢。)"],
  ["mardi", "[maʁ  di]", "星期二", "On se voit mardi   (我们星期二见。)"],
  ["mari", "[ma  ʁi]", "丈夫", "Mon mari travaille à l'hôpital   (我的丈夫在医院工作。)"],
  ["marié", "[ma  ʁje]", "已婚的（形容词）", "Il est marié avec Claire   (他和克莱尔结婚了。)"],
  ["mariés", "[ma  ʁje]", "已婚的（复数）", "Ils sont mariés depuis cinq ans   (他们结婚五年了。)"],
  ["marocain", "[ma  ʁɔ  kɛ̃]", "摩洛哥的", "Il est marocain   (他是摩洛哥人。)"],
  ["marron", "[maʁɔ̃]", "栗色的", "Il porte une veste marron   (他穿着栗色的外套。)"],
  ["mars", "[maʁs]", "三月", "Le mois de mars est froid   (三月很冷。)"],
  ["Marseille", "[maʁ  sɛj]", "马赛", "Marseille est une belle ville   (马赛是一个美丽的城市。)"],
  ["match", "[maʃ]", "比赛", "Le match commence à 20h   (比赛在晚上8点开始。)"],
  ["mathématiques", "[ma  ta  matik]", "数学", "Elle aime les mathématiques   (她喜欢数学。)"],
  ["matière", "[ma  tjɛʁ]", "学科", "La matière principale est les sciences   (主要学科是科学。)"],
  ["matin", "[ma  tɛ̃]", "早晨", "Le matin, il fait froid   (早晨很冷。)"],
  ["me", "[mə]", "我（宾格代词）", "Il me parle   (他说话给我听。)"],
  ["médecin", "[me  də  sɛ̃]", "医生", "Le médecin arrive bientôt   (医生马上就到。)"],
  ["meilleur", "[mɛ  jœʁ]", "最好的（阳性）", "C'est le meilleur film   (这是最好的电影。)"],
  ["meilleure", "[mɛ  jœʁ]", "最好的（阴性）", "Cette chanson est la meilleure   (这首歌是最好的。)"],
  ["meilleures", "[mɛ  jœʁ]", "最好的（复数阴性）", "Les meilleures idées viennent après le travail   (最好的想法是在工作后来的。)"],
  ["meilleurs", "[mɛ  jœʁ]", "最好的（复数阳性）", "Les meilleurs joueurs ont gagné   (最好的球员赢了。)"],
  ["même", "[mɛm]", "相同的，同样的", "Il a la même idée   (他有相同的想法。)"],
  ["mêmes", "[mɛm]", "相同的（复数）", "Nous avons les mêmes opinions   (我们有相同的意见。)"],
  ["mer", "[mɛʁ]", "海", "La mer est calme aujourd'hui   (今天海面平静。)"],
  ["merci", "[mɛʁ  si]", "谢谢", "Merci pour votre aide   (谢谢你的帮助。)"],
  ["mercredi", "[mɛʁ  kʁə  di]", "星期三", "Nous avons une réunion mercredi   (我们星期三开会。)"],
  ["mère", "[mɛʁ]", "母亲", "Ma mère prépare le dîner   (我妈妈准备晚餐。)"],
  ["mes", "[mɛ]", "我的（复数）", "Mes amis viennent ce soir   (我的朋友今晚来。)"],
  ["message", "[me  saʒ]", "信息", "Il m'a envoyé un message   (他给我发了个信息。)"],
  ["métier", "[me  tje]", "职业", "Il est médecin de métier   (他的职业是医生。)"],
  ["mètres", "[mɛtʁ]", "米（复数）", "La pièce mesure cinq mètres   (这个房间有五米长。)"],
  ["métro", "[me  tʁo]", "地铁", "Je prends le métro tous les jours   (我每天坐地铁。)"],
  ["mets", "[mɛ]", "放（我/你）", "Je mets mes clés sur la table   (我把钥匙放在桌子上。)"],
  ["mettent", "[mɛt]", "放（他们）", "Ils mettent les livres dans l'armoire   (他们把书放进柜子里。)"],
  ["mettez", "[mɛte]", "放（你们）", "Vous mettez la table   (你们摆桌子。)"],
  ["mettons", "[mɛt‿ɔ̃]", "放（我们）", "Nous mettons les chaises ici   (我们把椅子放在这里。)"],
  ["mettre", "[mɛtʁ]", "放", "Je vais mettre le livre sur l'étagère   (我要把书放在架子上。)"],
  ["Mexique", "[me  iksik]", "墨西哥", "Le Mexique est un pays d'Amérique   (墨西哥是一个美洲国家。)"],
  ["midi", "[mi  di]", "中午", "Il est midi   (现在是中午。)"],
  ["miel", "[mjɛl]", "蜂蜜", "Je mange du pain avec du miel   (我吃蜂蜜面包。)"],
  ["mieux", "[mjø]", "更好", "Il va mieux aujourd'hui   (他今天好多了。)"],
  ["mille", "[mil]", "一千", "Il a mille euros   (他有一千欧元。)"],
  ["million", "[mi  ljɔ̃]", "百万", "Il a gagné un million d'euros   (他赢得了一百万欧元。)"],
  ["millions", "[mi  ljɔ̃]", "百万（复数）", "Il y a des millions d'étoiles dans le ciel   (天上有数百万颗星星。)"],
  ["mince", "[mɛ̃s]", "苗条的，瘦的", "Elle est très mince   (她非常瘦。)"],
  ["minces", "[mɛ̃s]", "苗条的（复数）", "Elles sont minces et sportives   (她们又瘦又健壮。)"],
  ["minérale", "[mi  neʁal]", "矿物的", "L'eau minérale est bonne pour la santé   (矿泉水对健康有益。)"],
  ["minuit", "[mi  nɥi]", "午夜", "Il est minuit   (现在是午夜。)"],
  ["minute", "[mi  nyt]", "分钟", "Une minute, s'il vous plaît   (请等一分钟。)"],
  ["minutes", "[mi  nyt]", "分钟（复数）", "J'ai encore cinq minutes   (我还有五分钟。)"],
  ["miroir", "[mi  ʁwaʁ]", "镜子", "Il se regarde dans le miroir   (他在镜子里看自己。)"],
  ["moi", "[mwa]", "我（强调）", "C'est moi qui ai gagné   (是我赢了。)"],
  ["moins", "[mwɛ̃]", "更少", "Je veux moins de sucre   (我想要少一些糖。)"],
  ["moins de", "[mwɛ̃ də]", "少于", "Il a moins de livres que moi   (他比我少书。)"],
  ["mois", "[mwa]", "月", "Le mois de juin est chaud   (六月很热。)"],
  ["moment", "[mɔ  mɑ̃]", "时刻", "Ce moment est spécial   (这个时刻很特别。)"],
  ["mon", "[mɔ̃]", "我的（阳性）", "Mon frère est ici   (我的兄弟在这里。)"],
  ["monde", "[mɔ̃d]", "世界", "Le monde est beau   (这个世界很美。)"],
  ["monsieur", "[mə  sjøʁ]", "先生", "Monsieur Dupont est mon professeur   (Dupont先生是我的老师。)"],
  ["montagne", "[mɔ̃  taɲ]", "山", "La montagne est haute   (那座山很高。)"],
  ["Montmartre", "[mɔ̃  maʁtʁ]", "蒙马特（巴黎的区）", "Montmartre est célèbre pour ses artistes   (蒙马特因其艺术家而著名。)"],
  ["montre", "[mɔ̃tʁ]", "显示（动词）", "Il montre la photo   (他展示照片。)"],
  ["montrent", "[mɔ̃tʁ]", "显示（他们）", "Ils montrent leur travail   (他们展示他们的工作。)"],
  ["montrer", "[mɔ̃tʁe]", "展示", "Il veut montrer son dessin   (他想展示他的画。)"],
  ["montrez", "[mɔ̃tʁe]", "展示（你们）", "Montrez-moi le chemin   (给我指路。)"],
  ["monument", "[mɔ  ny  mɑ̃]", "纪念碑", "Le monument est en pierre   (纪念碑是石头做的。)"],
  ["monuments", "[mɔ  ny  mɑ̃]", "纪念碑（复数）", "Les monuments sont anciens   (这些纪念碑很古老。)"],
  ["mosquée", "[mɔs  kɛ]", "清真寺", "La mosquée est belle   (清真寺很美。)"],
  ["mot", "[mo]", "单词", "Il a appris ce mot   (他学会了这个单词。)"],
  ["mot de passe", "[mo də pas]", "密码", "Le mot de passe est secret   (密码是保密的。)"],
  ["mots", "[mo]", "单词（复数）", "J'ai écrit trois mots   (我写了三个单词。)"],
  ["murs", "[myʁ]", "墙（复数）", "Les murs sont blancs   (墙是白色的。)"],
  ["musée", "[my  ze]", "博物馆", "Le musée est fermé le lundi   (博物馆星期一闭馆。)"],
  ["musées", "[my  ze]", "博物馆（复数）", "Les musées sont intéressants   (这些博物馆很有趣。)"],
  ["musique", "[my  zik]", "音乐", "La musique est belle   (这音乐很美。)"],
];