var data = [
  ["n'", "[n‿]", "不（缩写）", "N'aime pas les légumes   (不喜欢蔬菜。)"],
  ["nage", "[naʒ]", "游泳（我/他）", "Je nage dans la piscine   (我在游泳池游泳。)"],
  ["nagent", "[naʒ]", "游泳（他们）", "Ils nagent dans la rivière   (他们在河里游泳。)"],
  ["nageons", "[naʒ‿ɔ̃]", "游泳（我们）", "Nous nageons ensemble   (我们一起游泳。)"],
  ["nager", "[naʒe]", "游泳", "J'aime nager le matin   (我喜欢早上游泳。)"],
  ["nagez", "[naʒe]", "游泳（你们）", "Vous nagez rapidement   (你们游得很快。)"],
  ["nationalité", "[na  sjɔ  na  li  te]", "国籍", "Quelle est votre nationalité ? (您的国籍是什么？)"],
  ["ne", "[nə]", "不", "Je ne veux pas partir   (我不想离开。)"],
  ["néerlandais", "[ne  ɛʁ  lɑ̃  dɛ]", "荷兰的（阳性）", "Il est néerlandais   (他是荷兰人。)"],
  ["néerlandaise", "[ne  ɛʁ  lɑ̃  dɛz]", "荷兰的（阴性）", "Elle est néerlandaise   (她是荷兰人。)"],
  ["néerlandaises", "[ne  ɛʁ  lɑ̃  dɛz]", "荷兰的（复数阴性）", "Les étudiantes sont néerlandaises   (这些学生是荷兰人。)"],
  ["neige", "[nɛʒ]", "下雪（动词）", "Il neige en hiver   (冬天下雪。)"],
  ["neiger", "[nɛʒe]", "下雪", "Il va neiger demain   (明天会下雪。)"],
  ["nettoie", "[nɛ  twa]", "清洁（我/他）", "Je nettoie la table   (我清洁桌子。)"],
  ["nettoient", "[nɛ  twa]", "清洁（他们）", "Elles nettoient la maison   (她们清洁房子。)"],
  ["nettoies", "[nɛ  twa]", "清洁（你）", "Tu nettoies ta chambre   (你清洁你的房间。)"],
  ["nettoyer", "[nɛ  twa  je]", "清洁", "J'aime nettoyer la cuisine   (我喜欢清洁厨房。)"],
  ["neuf", "[nœf]", "新的", "Ce téléphone est neuf   (这部手机是新的。)"],
  ["neuvième", "[nœ  viɛm]", "第九", "Elle habite au neuvième étage   (她住在第九层。)"],
  ["nez", "[ne]", "鼻子", "Mon nez est bouché   (我的鼻子堵了。)"],
  ["Noël", "[nɔ  ɛl]", "圣诞节", "Joyeux Noël ! (圣诞快乐！)"],
  ["noir", "[nwaʁ]", "黑色的（阳性）", "Son chapeau est noir   (他的帽子是黑色的。)"],
  ["noire", "[nwaʁ]", "黑色的（阴性）", "La robe est noire   (这条裙子是黑色的。)"],
  ["noires", "[nwaʁ]", "黑色的（复数阴性）", "Les chaussures sont noires   (这些鞋子是黑色的。)"],
  ["noirs", "[nwaʁ]", "黑色的（复数阳性）", "Les chats noirs portent chance   (黑猫带来好运。)"],
  ["nom", "[nɔ̃]", "名字", "Mon nom est Pierre   (我的名字是皮埃尔。)"],
  ["non", "[nɔ̃]", "不", "Non, merci   (不，谢谢。)"],
  ["non-fumeurs", "[nɔ̃ fy  mœʁ]", "禁烟区", "Cette salle est pour les non-fumeurs   (这个房间是禁烟区。)"],
  ["nord", "[nɔʁ]", "北方", "La ville est au nord   (城市在北方。)"],
  ["nos", "[no]", "我们的（复数）", "Nos enfants sont à l'école   (我们的孩子在学校。)"],
  ["notre", "[nɔ  tʁə]", "我们的", "C'est notre maison   (这是我们的房子。)"],
  ["Notre-Dame", "[nɔ  tʁə dam]", "巴黎圣母院", "Notre-Dame est magnifique   (巴黎圣母院很壮丽。)"],
  ["nourriture", "[nu  ʁi  tyʁ]", "食物", "La nourriture est délicieuse   (食物很美味。)"],
  ["nous", "[nu]", "我们", "Nous sommes prêts   (我们准备好了。)"],
  ["nous appelons", "[nu‿za  plɔ̃]", "我们叫", "Nous nous appelons Dupont   (我们叫杜邦。)"],
  ["nouveau", "[nu  vo]", "新的（阳性）", "Voici un nouveau livre   (这是一本新书。)"],
  ["nouveaux", "[nu  vo]", "新的（复数阳性）", "Les nouveaux élèves arrivent   (新学生来了。)"],
  ["nouvel", "[nu  vɛl]", "新的（阳性元音前）", "Un nouvel appartement   (一间新公寓。)"],
  ["nouvelle", "[nu  vɛl]", "新的（阴性）", "Une nouvelle voiture   (一辆新车。)"],
  ["nouvelles", "[nu  vɛl]", "新的（复数阴性）", "Les nouvelles chansons sont belles   (这些新歌很美。)"],
  ["novembre", "[nɔ  vɑ̃bʁ]", "十一月", "Novembre est un mois froid   (十一月是一个寒冷的月份。)"],
  ["nuages", "[nɥaʒ]", "云（复数）", "Les nuages couvrent le ciel   (云覆盖了天空。)"],
  ["nuit", "[nɥi]", "夜晚", "Bonne nuit ! (晚安！)"],
  ["nuits", "[nɥi]", "夜晚（复数）", "Les nuits d'été sont courtes   (夏天的夜晚很短。)"],
  ["numéro", "[ny  me  ʁo]", "号码", "Quel est ton numéro ? (你的号码是多少？)"],
];