var data = [
  ["occupé", "[ɔ  kype]", "忙碌的（阳性）", "Je suis occupé aujourd'hui   (我今天很忙。)"],
  ["occupées", "[ɔ  kype]", "忙碌的（复数阴性）", "Les filles sont occupées   (女孩们很忙。)"],
  ["octobre", "[ɔk  tɔbʁ]", "十月", "Octobre est un mois d'automne   (十月是秋天的月份。)"],
  ["office", "[ɔ  fis]", "办公室", "L'office est fermé le dimanche   (办公室周日关闭。)"],
  ["oiseau", "[wa  zo]", "鸟", "Un oiseau chante dans l'arbre   (一只鸟在树上唱歌。)"],
  ["oiseaux", "[wa  zo]", "鸟（复数）", "Les oiseaux volent dans le ciel   (鸟儿在天空中飞翔。)"],
  ["on", "[ɔ̃]", "我们/人们", "On va au cinéma ce soir   (我们今晚去电影院。)"],
  ["oncle", "[ɔ̃  klə]", "叔叔/舅舅", "Mon oncle habite à Paris   (我叔叔住在巴黎。)"],
  ["ont", "[ɔ̃]", "有（他们）", "Ils ont un grand jardin   (他们有一个大花园。)"],
  ["onze", "[ɔ̃z]", "十一", "J'ai onze ans   (我十一岁了。)"],
  ["opéra", "[o  pe  ʁa]", "歌剧院", "L'opéra est magnifique   (歌剧院很壮观。)"],
  ["opéras", "[o  pe  ʁa]", "歌剧院（复数）", "Les opéras sont célèbres ici   (这里的歌剧院很有名。)"],
  ["orange", "[ɔ  ʁɑ̃ʒ]", "橙子", "Je mange une orange   (我吃一个橙子。)"],
  ["oranges", "[ɔ  ʁɑ̃ʒ]", "橙子（复数）", "Les oranges sont délicieuses   (这些橙子很好吃。)"],
  ["ordinateur", "[ɔʁ  di  na  tœʁ]", "电脑", "Mon ordinateur est en panne   (我的电脑坏了。)"],
  ["oreille", "[ɔ  ʁɛj]", "耳朵", "Mon oreille me fait mal   (我的耳朵疼。)"],
  ["oreilles", "[ɔ  ʁɛj]", "耳朵（复数）", "Ses oreilles sont petites   (他的耳朵很小。)"],
  ["où", "[u]", "哪里", "Où est la station de métro ? (地铁站在哪里？)"],
  ["ou", "[u]", "或者", "Tu veux du thé ou du café ? (你想喝茶还是咖啡？)"],
  ["oublier", "[u  blje]", "忘记", "Je ne veux pas oublier cette journée   (我不想忘记这一天。)"],
  ["ouest", "[wɛst]", "西", "Le soleil se couche à l'ouest   (太阳在西方落下。)"],
  ["oui", "[wi]", "是", "Oui, je suis d'accord   (是的，我同意。)"],
  ["ouvert", "[u  vɛʁ]", "打开的（阳性）", "Le magasin est ouvert   (商店开着。)"],
  ["ouvre", "[uvʁ]", "打开（我/他）", "J'ouvre la porte   (我打开门。)"],
  ["ouvrent", "[uvʁ]", "打开（他们）", "Ils ouvrent leurs cahiers   (他们打开笔记本。)"],
  ["ouvres", "[uvʁ]", "打开（你）", "Tu ouvres la fenêtre   (你打开窗户。)"],
  ["ouvrez", "[uvʁe]", "打开（您/你们）", "Ouvrez vos livres à la page dix   (打开书到第十页。)"],
  ["ouvrir", "[uvʁiʁ]", "打开", "Je vais ouvrir une bouteille de vin   (我要打开一瓶酒。)"],
  ["ouvrons", "[uvʁɔ̃]", "打开（我们）", "Nous ouvrons les cadeaux ensemble   (我们一起打开礼物。)"],
];