var data = [
  ["pantalon", "[pɑ̃  ta  lɔ̃]", "裤子", "Il porte un pantalon noir   (他穿了一条黑裤子。)"],
  ["pantalons", "[pɑ̃  ta  lɔ̃]", "裤子（复数）", "Ces pantalons sont trop longs   (这些裤子太长了。)"],
  ["papa", "[pa  pa]", "爸爸", "Mon papa travaille à l'hôpital   (我爸爸在医院工作。)"],
  ["papier", "[pa  pje]", "纸", "J'écris sur du papier blanc   (我写在白纸上。)"],
  ["papy", "[pa  pi]", "爷爷", "Mon papy aime raconter des histoires   (我爷爷喜欢讲故事。)"],
  ["Pâques", "[pɑk]", "复活节", "Pâques est une fête importante   (复活节是一个重要的节日。)"],
  ["par exemple", "[paʁ ɛg  zɑ̃pl]", "例如", "Par exemple, il faut être poli   (例如，我们必须礼貌。)"],
  ["parc", "[paʁk]", "公园", "Les enfants jouent dans le parc   (孩子们在公园里玩。)"],
  ["parce qu'", "[paʁs kə]", "因为", "Il est en retard parce qu'il a raté le bus   (他迟到了，因为他错过了公交车。)"],
  ["parce que", "[paʁs kə]", "因为", "Je reste ici parce que je suis fatigué   (我留在这里因为我累了。)"],
  ["parcs", "[paʁk]", "公园（复数）", "Ces parcs sont magnifiques   (这些公园很漂亮。)"],
  ["pardon", "[paʁ  dɔ̃]", "对不起", "Pardon, où sont les toilettes ? (对不起，洗手间在哪里？)"],
  ["parents", "[pa  ʁɑ̃]", "父母", "Mes parents habitent à Lyon   (我父母住在里昂。)"],
  ["paresseuse", "[pa  ʁɛ  søz]", "懒惰的（阴性）", "Elle est paresseuse le dimanche   (她周日很懒惰。)"],
  ["paresseuses", "[pa  ʁɛ  søz]", "懒惰的（复数阴性）", "Ces filles sont paresseuses   (这些女孩很懒惰。)"],
  ["paresseux", "[pa  ʁɛ  sø]", "懒惰的（阳性）", "Il est parfois paresseux   (他有时很懒惰。)"],
  ["parfois", "[paʁ  fwa]", "有时", "Je vais au cinéma parfois   (我有时去看电影。)"],
  ["Paris", "[pa  ʁi]", "巴黎", "Paris est la capitale de la France   (巴黎是法国的首都。)"],
  ["parle", "[paʁl]", "说话（我/他）", "Il parle anglais couramment   (他流利地说英语。)"],
  ["parlent", "[paʁl]", "说话（他们）", "Ils parlent de leurs vacances   (他们在谈论他们的假期。)"],
  ["parler", "[paʁ  le]", "说话", "J'aime parler avec mes amis   (我喜欢和朋友聊天。)"],
  ["parles", "[paʁl]", "说话（你）", "Tu parles trop vite ! (你说得太快了！)"],
  ["parlez", "[paʁ  le]", "说话（您/你们）", "Parlez-vous français ? (您会说法语吗？)"],
  ["parlons", "[paʁ  lɔ̃]", "说话（我们）", "Parlons de ce projet   (我们谈谈这个项目吧。)"],
  ["pars", "[paʁ]", "离开（我/你）", "Je pars à 8 heures   (我八点出发。)"],
  ["part", "[paʁ]", "离开（他/她）", "Elle part en vacances demain   (她明天去度假。)"],
  ["partent", "[paʁt]", "离开（他们）", "Ils partent bientôt   (他们马上要走了。)"],
  ["partez", "[paʁ  te]", "离开（您/你们）", "Vous partez à quelle heure ? (您几点出发？)"],
  ["partie", "[paʁ  ti]", "部分", "Une partie du film était intéressante   (电影的一部分很有趣。)"],
  ["parties", "[paʁ  ti]", "部分（复数）", "Les deux parties ont signé l'accord   (双方签署了协议。)"],
  ["partir", "[paʁ  tiʁ]", "离开", "Il veut partir tôt demain matin   (他明天早上想早一点离开。)"],
  ["partons", "[paʁ  tɔ̃]", "离开（我们）", "Nous partons maintenant   (我们现在走。)"],
  ["pas", "[pa]", "不/没有", "Ce n'est pas possible   (这不可能。)"],
  ["passe", "[pas]", "经过/度过（我/他）", "Elle passe par ici tous les jours   (她每天从这里经过。)"],
  ["passeport", "[pas  pɔʁ]", "护照", "J'ai perdu mon passeport ! (我把护照弄丢了！)"],
  ["passeports", "[pas  pɔʁ]", "护照（复数）", "Les passeports sont nécessaires pour voyager   (护照是旅行必需品。)"],
  ["passer", "[pa  se]", "经过/度过", "Il veut passer l'été à la campagne   (他想在乡下度过夏天。)"],
  ["passez", "[pa  se]", "经过/度过（您/你们）", "Passez une bonne journée ! (祝您一天愉快！)"],
  ["pâtes", "[pɑt]", "面条", "Les pâtes sont prêtes   (面条煮好了。)"],
  ["Paul", "[pɔl]", "保罗（人名）", "Paul est mon meilleur ami   (保罗是我最好的朋友。)"],
  ["payer", "[pe  je]", "支付", "Je dois payer la facture   (我得付账单。)"],
  ["pays", "[pe  i]", "国家", "Mon pays est très beau   (我的国家很美丽。)"],
  ["Pays-Bas", "[pe  i  ba]", "荷兰", "Les Pays-Bas sont célèbres pour leurs tulipes   (荷兰因郁金香而闻名。)"],
  ["pêcher", "[pe  ʃe]", "钓鱼", "Il aime pêcher au bord de la rivière   (他喜欢在河边钓鱼。)"],
  ["peindre", "[pɛ̃dʁ]", "绘画", "Elle veut peindre un portrait   (她想画一幅肖像。)"],
  ["pendant", "[pɑ̃  dɑ̃]", "在      期间", "Il a étudié pendant deux heures   (他学习了两个小时。)"],
  ["père", "[pɛʁ]", "父亲", "Mon père est médecin   (我父亲是医生。)"],
  ["personne", "[pɛʁ  sɔn]", "人/某人/无人", "Il n'y a personne ici   (这里没有人。)"],
  ["personnes", "[pɛʁ  sɔn]", "人们", "Les personnes âgées aiment ce parc   (老人们喜欢这个公园。)"],
  ["petit", "[pəti]", "小的（阳性）", "Un petit chat dort sur le canapé   (一只小猫在沙发上睡觉。)"],
  ["petit ami", "[pəti ami]", "男朋友", "Son petit ami est très gentil   (她的男朋友很温柔。)"],
  ["petit déjeuner", "[pəti deʒœne]", "早餐", "Nous prenons le petit déjeuner à 8 heures   (我们八点吃早餐。)"],
  ["petit frère", "[pəti fʁɛʁ]", "弟弟", "Mon petit frère adore les jeux vidéo   (我弟弟喜欢电子游戏。)"],
  ["petite", "[pətit]", "小的（阴性）", "Une petite maison se trouve ici   (这儿有一座小房子。)"],
  ["petite amie", "[pətit ami]", "女朋友", "Il a une petite amie charmante   (他有一位迷人的女朋友。)"],
  ["petite sœur", "[pətit søʁ]", "妹妹", "Sa petite sœur est très mignonne   (他妹妹很可爱。)"],
  ["petite-fille", "[pətit fij]", "孙女", "Sa petite-fille habite à Paris   (他的孙女住在巴黎。)"],
  ["petites", "[pətit]", "小的（复数阴性）", "Les petites fleurs sont rouges   (这些小花是红色的。)"],
  ["petits", "[pəti]", "小的（复数阳性）", "Les petits enfants jouent dehors   (小孩子们在外面玩。)"],
  ["petits-enfants", "[pəti zɑ̃  fɑ̃]", "孙子孙女", "Mes petits-enfants viennent ce week-end   (我的孙子孙女这周末会来。)"],
  ["petits-fils", "[pəti fis]", "孙子", "Mon petit-fils est très intelligent   (我的孙子非常聪明。)"],
  ["peut", "[pø]", "能（他/她）", "Il peut venir avec nous   (他可以和我们一起来。)"],
  ["peuvent", "[pœv]", "能（他们）", "Elles peuvent parler espagnol   (她们会说西班牙语。)"],
  ["peux", "[pø]", "能（我/你）", "Tu peux m'aider, s'il te plaît ? (你能帮我一下吗？)"],
  ["pharmacie", "[faʁ  ma  si]", "药店", "La pharmacie est ouverte jusqu'à 19h   (药店营业到晚上7点。)"],
  ["pharmacies", "[faʁ  ma  si]", "药店（复数）", "Il y a trois pharmacies dans cette rue   (这条街有三家药店。)"],
  ["photo", "[fo  to]", "照片", "Cette photo est très belle   (这张照片很漂亮。)"],
  ["photographes", "[fo  to  gʁaf]", "摄影师", "Les photographes prennent des images magnifiques   (摄影师们拍摄了很棒的照片。)"],
  ["phrase", "[fʁɑz]", "句子", "Cette phrase est difficile à comprendre   (这个句子很难理解。)"],
  ["phrases", "[fʁɑz]", "句子（复数）", "Les phrases dans ce livre sont longues   (这本书里的句子很长。)"],
  ["physique", "[fi  zik]", "物理/身体", "Il est bon en physique   (他擅长物理。)"],
  ["piano", "[pja  no]", "钢琴", "Elle joue du piano depuis cinq ans   (她学钢琴已经五年了。)"],
  ["pièce", "[pjɛs]", "房间/片段", "Cette pièce est lumineuse   (这个房间很明亮。)"],
  ["pièces", "[pjɛs]", "房间/片段（复数）", "Les pièces de cet appartement sont grandes   (这套公寓的房间很大。)"],
  ["pied", "[pje]", "脚", "Il a mal au pied gauche   (他左脚疼。)"],
  ["pique-nique", "[pik nik]", "野餐", "Nous allons faire un pique-nique au parc   (我们要去公园野餐。)"],
  ["piscine", "[pi  sin]", "游泳池", "La piscine est fermée aujourd'hui   (游泳池今天关闭。)"],
  ["pizza", "[pit  sa]", "披萨", "J'adore manger de la pizza   (我喜欢吃披萨。)"],
  ["pizzas", "[pit  sa]", "披萨（复数）", "Ces pizzas sont délicieuses   (这些披萨很好吃。)"],
  ["placards", "[pla  kaʁ]", "橱柜（复数）", "Les placards de la cuisine sont neufs   (厨房的橱柜是新的。)"],
  ["place", "[plas]", "地方/座位", "Il reste une place pour toi   (还有一个座位留给你。)"],
  ["plage", "[plaʒ]", "海滩", "Nous passons nos vacances à la plage   (我们在海滩度假。)"],
  ["plan", "[plɑ̃]", "计划/地图", "Voici le plan de la ville   (这是城市地图。)"],
  ["plante", "[plɑ̃t]", "植物", "Cette plante a besoin de beaucoup de soleil   (这种植物需要很多阳光。)"],
  ["plantes", "[plɑ̃t]", "植物（复数）", "Les plantes de ce jardin sont magnifiques   (这个花园的植物很美丽。)"],
  ["pleut", "[plø]", "下雨", "Il pleut depuis ce matin   (从早上开始就下雨了。)"],
  ["pleuvoir", "[plø  vwaʁ]", "下雨", "Il peut pleuvoir demain   (明天可能会下雨。)"],
  ["plongée", "[plɔ̃  ʒe]", "潜水", "La plongée est son activité préférée   (潜水是他最喜欢的活动。)"],
  ["pluie", "[plɥi]", "雨", "La pluie est forte aujourd'hui   (今天雨下得很大。)"],
  ["plus", "[ply]", "更多/更", "Il a plus de patience que moi   (他比我更有耐心。)"],
  ["plus de", "[ply də]", "超过", "Il y a plus de 50 personnes ici   (这里有超过50人。)"],
  ["polonais", "[pɔ  lɔ  nɛ]", "波兰的/波兰人（阳性）", "Il est polonais   (他是波兰人。)"],
  ["polonaise", "[pɔ  lɔ  nɛz]", "波兰的/波兰人（阴性）", "Elle est polonaise   (她是波兰人。)"],
  ["pommes de terre", "[pɔm də tɛʁ]", "土豆", "Les pommes de terre sont sur la table   (土豆在桌子上。)"],
  ["pont", "[pɔ̃]", "桥", "Ce pont est très célèbre   (这座桥非常有名。)"],
  ["portable", "[pɔʁ  ta  bl]", "手机", "Mon portable est en charge   (我的手机在充电。)"],
  ["porte", "[pɔʁt]", "门", "La porte est fermée   (门是关着的。)"],
  ["Portugal", "[pɔʁ  tu  ɡal]", "葡萄牙", "Je veux visiter le Portugal   (我想去葡萄牙。)"],
  ["pose", "[poz]", "提出/摆放（我/他）", "Elle pose une question intéressante   (她提出了一个有趣的问题。)"],
  ["poser", "[po  ze]", "提出/摆放", "Puis-je poser mon sac ici ? (我可以把包放在这里吗？)"],
  ["possible", "[pɔ  si  bl]", "可能的", "C'est possible de partir maintenant   (现在可以离开了。)"],
  ["poubelle", "[pu  bɛl]", "垃圾桶", "Jette ce papier dans la poubelle   (把这张纸丢进垃圾桶。)"],
  ["pour", "[puʁ]", "为了/给", "Ce cadeau est pour toi   (这个礼物是给你的。)"],
  ["pourquoi", "[puʁ  kwa]", "为什么", "Pourquoi es-tu en retard ? (你为什么迟到了？)"],
  ["prendre", "[pʁɑ̃dʁ]", "拿/取", "Je vais prendre un café   (我要喝一杯咖啡。)"],
  ["près de", "[pʁɛ də]", "靠近", "Il habite près de la gare   (他住在车站附近。)"],
  ["prêt", "[pʁɛ]", "准备好的（阳性）", "Il est prêt à partir   (他准备好了出发。)"],
  ["prête", "[pʁɛt]", "准备好的（阴性）", "Elle est prête pour l'examen   (她为考试准备好了。)"],
  ["prix", "[pʁi]", "价格", "Le prix de ce livre est élevé   (这本书的价格很高。)"],
  ["problème", "[pʁɔ  blɛm]", "问题", "Il y a un problème avec la voiture   (汽车出了问题。)"],
  ["problème de santé", "[pʁɔ  blɛm də sɑ̃  te]", "健康问题", "Elle a des problèmes de santé   (她有健康问题。)"],
  ["professeur", "[pʁo  fɛ  sœʁ]", "老师", "Le professeur est très gentil   (老师很和蔼。)"],
  ["professeurs", "[pʁo  fɛ  sœʁ]", "老师（复数）", "Les professeurs sont en réunion   (老师们正在开会。)"],
  ["progrès", "[pʁɔ  gʁɛ]", "进步", "Tu fais beaucoup de progrès en français   (你在法语上进步很大。)"],
  ["projet", "[pʁo  ʒɛ]", "项目", "Ce projet est très ambitieux   (这个项目非常有雄心。)"],
  ["projets", "[pʁo  ʒɛ]", "项目（复数）", "Ils travaillent sur plusieurs projets   (他们正在做几个项目。)"],
  ["promenade", "[pʁɔ  mə  nad]", "散步", "Une promenade au parc est agréable   (在公园散步很愉快。)"],
  ["promener", "[pʁɔ  mə  ne]", "遛/散步", "Elle aime promener son chien   (她喜欢遛狗。)"],
  ["propre", "[pʁɔpʁ]", "干净的/自己的", "Cette maison est très propre   (这个房子很干净。)"],
  ["proposer", "[pʁo  po  ze]", "提议", "Je propose de partir tôt   (我建议早点出发。)"],
  ["protéger", "[pʁo  te  ʒe]", "保护", "Il faut protéger l'environnement   (我们必须保护环境。)"],
  ["pluie", "[plɥi]", "雨", "La pluie tombe doucement   (雨轻轻地下着。)"],
  ["public", "[py  blik]", "公众", "Le public applaudit le spectacle   (观众为演出鼓掌。)"],
  ["publique", "[py  blik]", "公共的", "Une bibliothèque publique est ouverte à tous   (公共图书馆向所有人开放。)"],
  ["publicité", "[py  bli  si  te]", "广告", "Cette publicité est très créative   (这个广告很有创意。)"],
  ["puissant", "[pɥi  sɑ̃]", "强大的", "Ce moteur est très puissant   (这个发动机非常强大。)"],
];