var data = [
  ["qu'", "[kə]", "什么", "Qu'est-ce que tu veux dire ? (你想说什么？)"],
  ["quand", "[kɑ̃]", "什么时候/当      时候", "Quand pars-tu en vacances ? (你什么时候去度假？)"],
  ["quarante", "[ka  ʁɑ̃t]", "四十", "Il y a quarante élèves dans la classe   (班上有四十名学生。)"],
  ["quart", "[kaʁ]", "四分之一", "Un quart de la pizza a été mangé   (四分之一的披萨被吃掉了。)"],
  ["quartier", "[kaʁ  tje]", "街区/社区", "Ce quartier est très animé   (这个街区非常热闹。)"],
  ["Quartier latin", "[kaʁ  tje la  tɛ̃]", "拉丁区", "Le Quartier latin est connu pour ses universités   (拉丁区以其大学而闻名。)"],
  ["quatorze", "[ka  tɔʁz]", "十四", "Elle a quatorze ans   (她十四岁了。)"],
  ["quatre", "[katʁ]", "四", "J'ai acheté quatre pommes   (我买了四个苹果。)"],
  ["quatre-vingt", "[katʁ  vɛ̃]", "八十", "Quatre-vingt personnes ont participé   (八十人参加了。)"],
  ["quatre-vingts", "[katʁ  vɛ̃]", "八十（复数形式）", "Les quatre-vingts invités sont arrivés   (八十位客人都到了。)"],
  ["quatrième", "[ka  tʁi  ɛm]", "第四", "C'est le quatrième livre de la série   (这是这套书的第四本。)"],
  ["que", "[kə]", "什么/谁", "Que fais-tu ? (你在做什么？)"],
  ["Québec", "[ke  bɛk]", "魁北克", "Québec est une ville historique au Canada   (魁北克是加拿大的一座历史名城。)"],
  ["quel", "[kɛl]", "哪个/什么（阳性）", "Quel est ton plat préféré ? (你最喜欢的菜是什么？)"],
  ["quelle", "[kɛl]", "哪个/什么（阴性）", "Quelle heure est-il ? (现在几点了？)"],
  ["quelqu'un", "[kɛl  kœ̃]", "某人", "Quelqu'un a frappé à la porte   (有人敲门了。)"],
  ["quelque chose", "[kɛl  kə ʃoz]", "某事", "J'ai quelque chose à te dire   (我有件事要告诉你。)"],
  ["quelques", "[kɛlk]", "一些", "Quelques élèves sont absents aujourd'hui   (今天有一些学生缺席。)"],
  ["question", "[kɛs  tjɔ̃]", "问题", "As-tu une question à poser ? (你有问题要问吗？)"],
  ["qui", "[ki]", "谁", "Qui est là ? (谁在那儿？)"],
  ["quinze", "[kɛ̃z]", "十五", "Il est quinze heures   (现在是下午三点。)"],
  ["quoi", "[kwa]", "什么", "Tu veux boire quoi ? (你想喝什么？)"],
];