var data = [
  ["radio", "[ʁa  djo]", "收音机", "J'écoute la radio tous les matins   (我每天早上都听收音机。)"],
  ["raison", "[ʁɛ  zɔ̃]", "理由", "Il a raison de partir tôt   (他早点离开是有道理的。)"],
  ["rapide", "[ʁa  pid]", "快的", "Le train est très rapide   (火车非常快。)"],
  ["rapidement", "[ʁa  pi  də  mɑ̃]", "快速地", "Elle court rapidement   (她跑得很快。)"],
  ["réception", "[ʁe  sɛp  sjɔ̃]", "接待", "La réception est ouverte 24h/24   (接待处全天开放。)"],
  ["regarde", "[ʁə  ɡaʁd]", "看", "Il regarde la télévision   (他在看电视。)"],
  ["regardent", "[ʁə  ɡaʁd]", "看（复数）", "Ils regardent un film   (他们在看电影。)"],
  ["regarder", "[ʁə  ɡaʁ  de]", "看", "J'aime regarder les étoiles   (我喜欢看星星。)"],
  ["regardes", "[ʁə  ɡaʁd]", "你看", "Tu regardes quoi ? (你在看什么？)"],
  ["rencontrer", "[ʁɑ̃  kɔ̃  tʁe]", "遇见", "Je vais rencontrer mes amis   (我要去见我的朋友们。)"],
  ["rentre", "[ʁɑ̃tʁ]", "回来", "Il rentre à la maison après le travail   (他下班后回家。)"],
  ["rentrer", "[ʁɑ̃tʁe]", "回家/回去", "Elle doit rentrer avant 20h   (她必须在晚上8点前回家。)"],
  ["rentres", "[ʁɑ̃tʁ]", "你回", "Tu rentres ce soir ? (你今晚回来吗？)"],
  ["repas", "[ʁə  pɑ]", "餐", "Le repas est prêt   (饭准备好了。)"],
  ["répond", "[ʁe  pɔ̃]", "回答", "Il répond à la question du professeur   (他回答老师的问题。)"],
  ["répondent", "[ʁe  pɔ̃d]", "回答（复数）", "Les élèves répondent correctement   (学生们回答得很正确。)"],
  ["répondez", "[ʁe  pɔ̃  de]", "您回答", "Répondez à cette lettre rapidement   (请尽快回复这封信。)"],
  ["répondons", "[ʁe  pɔ̃  dɔ̃]", "我们回答", "Nous répondons aux emails chaque matin   (我们每天早上回复电子邮件。)"],
  ["répondre", "[ʁe  pɔ̃dʁ]", "回答", "Je vais répondre à sa question   (我要回答他的问题。)"],
  ["réponds", "[ʁe  pɔ̃]", "我回答", "Je réponds toujours honnêtement   (我总是诚实地回答。)"],
  ["réponse", "[ʁe  pɔ̃s]", "答案", "Quelle est la réponse correcte ? (正确答案是什么？)"],
  ["réserve", "[ʁe  zɛʁv]", "预订", "Je réserve une table pour deux   (我预订了一张两人桌。)"],
  ["réserver", "[ʁe  zɛʁ  ve]", "预订", "Il faut réserver une chambre   (需要预订一个房间。)"],
  ["réserves", "[ʁe  zɛʁv]", "你预订", "Tu réserves une place pour moi ? (你帮我预订一个座位吗？)"],
  ["réservons", "[ʁe  zɛʁ  vɔ̃]", "我们预订", "Nous réservons des billets pour le concert   (我们在为演唱会预订门票。)"],
  ["responsables", "[ʁɛ  spõ  sabl]", "负责的", "Ils sont responsables de ce projet   (他们负责这个项目。)"],
  ["ressemble", "[ʁə  sɑ̃  bl]", "相似", "Ce garçon ressemble à son père   (这个男孩长得像他爸爸。)"],
  ["ressemblent", "[ʁə  sɑ̃  bl]", "相似（复数）", "Les deux maisons se ressemblent   (这两座房子很相似。)"],
  ["ressemblez", "[ʁə  sɑ̃  ble]", "您相似", "Vous ressemblez à votre frère   (您和您的兄弟很像。)"],
  ["restaurant", "[ʁɛs  to  ʁɑ̃]", "餐厅", "Ce restaurant est très célèbre   (这家餐厅非常有名。)"],
  ["restaurants", "[ʁɛs  to  ʁɑ̃]", "餐厅（复数）", "Les restaurants italiens sont délicieux   (意大利餐厅很美味。)"],
  ["reste", "[ʁɛst]", "留下", "Il reste à la maison aujourd'hui   (他今天待在家里。)"],
  ["rester", "[ʁɛs  te]", "停留", "Nous allons rester ici quelques jours   (我们会在这里待几天。)"],
  ["restes", "[ʁɛst]", "你留下", "Tu restes avec nous ce soir ? (你今晚和我们待在一起吗？)"],
  ["restez", "[ʁɛs  te]", "您留下", "Restez ici, je reviens tout de suite   (请待在这里，我马上回来。)"],
  ["retard", "[ʁə  taʁ]", "迟到", "Désolé pour le retard   (抱歉迟到了。)"],
  ["retourne", "[ʁə  tuʁn]", "返回", "Elle retourne à Paris demain   (她明天返回巴黎。)"],
  ["retourner", "[ʁə  tuʁ  ne]", "返回", "Il veut retourner dans son pays natal   (他想回到他的家乡。)"],
  ["retournons", "[ʁə  tuʁ  nɔ̃]", "我们返回", "Nous retournons chez nous après le dîner   (我们晚饭后回家。)"],
  ["réunion", "[ʁe  y  njɔ̃]", "会议", "La réunion commence à 14h   (会议在下午两点开始。)"],
  ["réveille", "[ʁe  vɛj]", "唤醒", "Il réveille son frère tôt le matin   (他早晨叫醒了他弟弟。)"],
  ["réveiller", "[ʁe  vɛ  je]", "唤醒", "Peux-tu me réveiller à 7h ? (你能在7点叫醒我吗？)"],
  ["revenez", "[ʁə  və  ne]", "您回来", "Revenez demain pour les résultats   (请明天回来拿结果。)"],
  ["revenir", "[ʁə  və  niʁ]", "回来", "Je vais revenir plus tard   (我稍后会回来。)"],
  ["revenons", "[ʁə  və  nɔ̃]", "我们回来", "Nous revenons chaque année pour les vacances   (我们每年都回来度假。)"],
  ["reviennent", "[ʁə  vjɛn]", "他们回来", "Ils reviennent de leur voyage   (他们从旅途中回来。)"],
  ["reviens", "[ʁə  vjɛ̃]", "我回来", "Je reviens dans une heure   (我一小时后回来。)"],
  ["revient", "[ʁə  vjɛ̃]", "他回来", "Elle revient avec un cadeau   (她带着礼物回来。)"],
  ["rez-de-chaussée", "[ʁɛ  də  ʃo  se]", "底楼", "L'appartement est au rez-de-chaussée   (公寓在底楼。)"],
  ["rien", "[ʁjɛ̃]", "没有", "Il n'y a rien dans le frigo   (冰箱里什么都没有。)"],
  ["rivière", "[ʁi  vjɛʁ]", "河流", "Cette rivière traverse la ville   (这条河流穿过城市。)"],
  ["riz", "[ʁi]", "米饭", "Nous mangeons du riz tous les jours   (我们每天都吃米饭。)"],
  ["robe", "[ʁɔb]", "连衣裙", "Elle porte une belle robe rouge   (她穿着一件漂亮的红色连衣裙。)"],
  ["robes", "[ʁɔb]", "连衣裙（复数）", "Les robes sont en solde aujourd'hui   (连衣裙今天打折。)"],
  ["Rome", "[ʁɔm]", "罗马", "Rome est une ville magnifique   (罗马是一个美丽的城市。)"],
  ["rouge", "[ʁuʒ]", "红色", "J'aime le rouge   (我喜欢红色。)"],
  ["rouges", "[ʁuʒ]", "红色的（复数）", "Les fleurs rouges sont magnifiques   (红色的花非常美丽。)"],
  ["route", "[ʁut]", "道路", "La route est longue   (这条路很长。)"],
  ["routes", "[ʁut]", "道路（复数）", "Les routes de campagne sont calmes   (乡间小路很安静。)"],
  ["Royaume-Uni", "[ʁwa  jom  y  ni]", "英国", "Le Royaume-Uni est un pays européen   (英国是一个欧洲国家。)"],
  ["rue", "[ʁy]", "街道", "Il habite dans une petite rue   (他住在一条小街上。)"],
  ["rues", "[ʁy]", "街道（复数）", "Les rues de Paris sont célèbres   (巴黎的街道很有名。)"],
  ["russe", "[ʁys]", "俄国的/俄语的", "Il parle russe couramment   (他会说流利的俄语。)"],
];