var data = [
  ["s'", "[sə]", "自己/自身", "Il s'habille vite   (他穿得很快。)"],
  ["s'appelle", "[sa  pɛl]", "叫/名叫", "Elle s'appelle Marie   (她叫玛丽。)"],
  ["s'appellent", "[sa  pɛl]", "叫/名叫（复数）", "Ils s'appellent Jacques et Pierre   (他们叫雅克和皮埃尔。)"],
  ["s'il te plaît", "[sil tə plɛ]", "请（非正式）", "Passe-moi le sel, s'il te plaît   (请把盐递给我。)"],
  ["s'il vous plaît", "[sil vu plɛ]", "请（正式）", "Pourriez-vous répéter, s'il vous plaît ? (您能再说一遍吗？)"],
  ["sa", "[sa]", "她的/他的", "Elle a oublié sa clé   (她忘了她的钥匙。)"],
  ["sac", "[sak]", "袋子", "J'ai un sac en cuir   (我有一个皮包。)"],
  ["sac à dos", "[sak‿a‿do]", "背包", "Mon sac à dos est lourd   (我的背包很重。)"],
  ["Sacré-Cœur", "[sa  kʁe‿kœʁ]", "圣心教堂", "Nous visitons le Sacré-Cœur   (我们参观了圣心教堂。)"],
  ["sacs", "[sak]", "袋子（复数）", "Ces sacs sont en plastique   (这些袋子是塑料的。)"],
  ["sacs à dos", "[sak‿a‿do]", "背包（复数）", "Les élèves portent des sacs à dos   (学生们背着背包。)"],
  ["sais", "[sɛ]", "知道", "Je sais la réponse   (我知道答案。)"],
  ["saison", "[sɛ  zɔ̃]", "季节", "L'été est ma saison préférée   (夏天是我最喜欢的季节。)"],
  ["saisons", "[sɛ  zɔ̃]", "季节（复数）", "Les quatre saisons sont magnifiques   (四季都很美丽。)"],
  ["sait", "[sɛ]", "知道（第三人称单数）", "Il sait parler espagnol   (他会说西班牙语。)"],
  ["salle", "[sal]", "房间/大厅", "La salle est grande et lumineuse   (房间宽敞明亮。)"],
  ["salle de bains", "[sal də bɛ̃]", "浴室", "La salle de bains est occupée   (浴室正在使用。)"],
  ["salle de classe", "[sal də klas]", "教室", "La salle de classe est vide   (教室是空的。)"],
  ["salles", "[sal]", "房间/大厅（复数）", "Les salles sont bien décorées   (房间装饰得很漂亮。)"],
  ["salon", "[sa  lɔ̃]", "客厅", "Nous regardons la télé dans le salon   (我们在客厅看电视。)"],
  ["salut", "[sa  ly]", "你好/再见（口语）", "Salut, comment ça va ? (你好，最近怎么样？)"],
  ["samedi", "[sam  di]", "星期六", "Nous sortons samedi soir   (我们周六晚上出去玩。)"],
  ["sans", "[sɑ̃]", "没有/无", "Il est parti sans dire au revoir   (他没说再见就走了。)"],
  ["savent", "[sa  vɑ̃]", "知道（复数）", "Ils savent nager   (他们会游泳。)"],
  ["savez", "[sa  ve]", "知道（第二人称）", "Vous savez où est la gare ? (您知道火车站在哪吗？)"],
  ["savoir", "[sa  vwaʁ]", "知道/了解", "Elle veut savoir la vérité   (她想知道真相。)"],
  ["savons", "[sa  vɔ̃]", "知道（第一人称复数）", "Nous savons qu'il viendra   (我们知道他会来。)"],
  ["se", "[sə]", "自己/彼此", "Il se lève tôt   (他起得很早。)"],
  ["Seine", "[sɛn]", "塞纳河", "La Seine traverse Paris   (塞纳河流经巴黎。)"],
  ["seize", "[sɛz]", "十六", "Elle a seize ans   (她十六岁。)"],
  ["sel", "[sɛl]", "盐", "Peux-tu me passer le sel ? (你能把盐递给我吗？)"],
  ["semaine", "[sə  mɛn]", "星期", "La semaine prochaine, nous partons en vacances   (下周我们去度假。)"],
  ["semestre", "[sə  mɛstʁ]", "学期", "Le premier semestre est terminé   (第一学期结束了。)"],
  ["sens", "[sɑ̃]", "感觉/感觉到", "Je sens une odeur de fleurs   (我闻到了花香。)"],
  ["sent", "[sɑ̃]", "感觉（第三人称单数）", "Elle sent le vent sur son visage   (她感受到了脸上的风。)"],
  ["sentent", "[sɑ̃t]", "感觉（复数）", "Ils sentent la chaleur du soleil   (他们感受到太阳的温暖。)"],
  ["sentez", "[sɑ̃  te]", "感觉（第二人称）", "Vous sentez ce parfum ? (你闻到这个香水了吗？)"],
  ["sentir", "[sɑ̃  tiʁ]", "感觉/闻到", "Je peux sentir la fumée   (我能闻到烟味。)"],
  ["sentons", "[sɑ̃  tɔ̃]", "感觉（第一人称复数）", "Nous sentons la pluie arriver   (我们感觉到雨要来了。)"],
  ["sept", "[sɛt]", "七", "Il y a sept jours dans une semaine   (一周有七天。)"],
  ["septembre", "[sɛp  tɑ̃bʁ]", "九月", "L'école commence en septembre   (学校九月开学。)"],
  ["septième", "[sɛ  tjɛm]", "第七", "Il habite au septième étage   (他住在七楼。)"],
  ["série", "[se  ʁi]", "系列", "Je regarde une série à la télé   (我在看一部电视剧。)"],
  ["séries", "[se  ʁi]", "系列（复数）", "Ces séries sont très populaires   (这些系列很受欢迎。)"],
  ["serviette", "[sɛʁ  vjɛt]", "毛巾/餐巾", "J'ai besoin d'une serviette propre   (我需要一条干净的毛巾。)"],
  ["serviettes", "[sɛʁ  vjɛt]", "毛巾/餐巾（复数）", "Les serviettes sont dans la salle de bains   (毛巾在浴室里。)"],
  ["ses", "[se]", "他/她的（复数）", "Il a oublié ses clés   (他忘了他的钥匙。)"],
  ["seulement", "[sœl  mɑ̃]", "仅仅/只有", "Elle a seulement dix euros   (她只有十欧元。)"],
  ["si", "[si]", "如果", "Si tu veux, on peut partir maintenant   (如果你想，我们可以现在出发。)"],
  ["simple", "[sɛ̃  pl]", "简单的", "C'est un problème simple   (这是个简单的问题。)"],
  ["six", "[sis]", "六", "Il a six stylos   (他有六支钢笔。)"],
  ["sixième", "[si  zjɛm]", "第六", "Elle est en sixième classe   (她上六年级。)"],
  ["ski", "[ski]", "滑雪", "J'adore faire du ski en hiver   (我喜欢冬天滑雪。)"],
  ["soif", "[swaf]", "渴", "J'ai soif, je vais boire de l'eau   (我渴了，我要喝水。)"],
  ["soir", "[swaʁ]", "晚上", "Nous dînons ensemble ce soir   (我们今晚一起吃晚饭。)"],
  ["soixante", "[swa  sɑ̃t]", "六十", "Il y a soixante secondes dans une minute   (一分钟有六十秒。)"],
  ["sol", "[sɔl]", "地面", "Il y a un tapis sur le sol   (地上有一块地毯。)"],
  ["soleil", "[sɔ  lɛj]", "太阳", "Le soleil brille aujourd'hui   (今天太阳很明亮。)"],
  ["sommeil", "[sɔ  mɛj]", "睡眠", "Il manque de sommeil   (他缺乏睡眠。)"],
  ["sommes", "[sɔm]", "是（第一人称复数）", "Nous sommes heureux ici   (我们在这里很开心。)"],
  ["son", "[sɔ̃]", "他的/她的（阳性单数）", "Il a oublié son livre   (他忘了他的书。)"],
  ["sont", "[sɔ̃]", "是（第三人称复数）", "Ils sont en vacances   (他们在度假。)"],
  ["sors", "[sɔʁ]", "出去（第一/第二人称单数）", "Je sors tous les soirs   (我每天晚上出去。)"],
  ["sort", "[sɔʁ]", "出去（第三人称单数）", "Elle sort avec ses amis   (她和朋友出去。)"],
  ["sortent", "[sɔʁt]", "出去（第三人称复数）", "Les enfants sortent jouer dans le jardin   (孩子们出去花园玩。)"],
  ["sortez", "[sɔʁ  te]", "出去（第二人称复数）", "Sortez par cette porte   (从这扇门出去。)"],
  ["sortir", "[sɔʁ  tiʁ]", "出去", "Je vais sortir ce soir   (我今晚要出去。)"],
  ["sortons", "[sɔʁ  tɔ̃]", "出去（第一人称复数）", "Nous sortons souvent ensemble   (我们经常一起出去。)"],
  ["souris", "[su  ʁi]", "老鼠", "J'ai vu une souris dans la cuisine   (我在厨房看到了一只老鼠。)"],
  ["sous", "[su]", "在……下面", "Le chat est caché sous le lit   (猫藏在床下。)"],
  ["souvenez", "[su  v(ə)  ne]", "记得（第二人称复数）", "Vous souvenez-vous de cet endroit ? (你还记得这个地方吗？)"],
  ["souvenir", "[su  v(ə)  niʁ]", "记得/回忆", "Je me souviens de notre voyage   (我记得我们的旅行。)"],
  ["souvenirs", "[su  v(ə)  niʁ]", "回忆（复数）", "Ces photos me rappellent de beaux souvenirs   (这些照片让我想起了美好的回忆。)"],
  ["souvenons", "[su  v(ə)  nɔ̃]", "记得（第一人称复数）", "Nous nous souvenons bien de lui   (我们对他记忆犹新。)"],
  ["souvent", "[su  vɑ̃]", "经常", "Elle va souvent au cinéma   (她经常去电影院。)"],
  ["souviens", "[su  vjɛ̃]", "记得（第一/第二人称单数）", "Je me souviens de ce jour   (我记得那一天。)"],
  ["sport", "[spɔʁ]", "运动", "Le football est mon sport préféré   (足球是我最喜欢的运动。)"],
  ["stations", "[sta  sjɔ̃]", "车站（复数）", "Les stations de métro sont bondées   (地铁站很拥挤。)"],
  ["stressé", "[stʁɛ  se]", "紧张的（阳性单数）", "Il est stressé avant l'examen   (他考试前很紧张。)"],
  ["stressée", "[stʁɛ  se]", "紧张的（阴性单数）", "Elle est stressée à cause du travail   (她因为工作而紧张。)"],
  ["stressés", "[stʁɛ  se]", "紧张的（阳性复数）", "Les étudiants sont stressés avant les résultats   (学生们在成绩出来前很紧张。)"],
  ["stylo", "[sti  lo]", "钢笔", "J'écris avec un stylo bleu   (我用蓝色的钢笔写字。)"],
  ["sucre", "[sykʁ]", "糖", "Je mets du sucre dans mon café   (我在咖啡里加糖。)"],
  ["sud", "[syd]", "南方", "Nous partons pour le sud de la France   (我们前往法国南部。)"],
  ["suis", "[sɥi]", "是（第一人称单数）", "Je suis étudiant   (我是学生。)"],
  ["suisses", "[sɥis]", "瑞士的", "Les montres suisses sont célèbres   (瑞士手表很有名。)"],
  ["super", "[sy  pɛʁ]", "棒的", "Ce film est super ! (这部电影太棒了！)"],
  ["supermarché", "[sy  pɛʁ  maʁ  ʃe]", "超市", "Je vais au supermarché acheter du pain   (我要去超市买面包。)"],
  ["sûr", "[syʁ]", "确信的（阳性单数）", "Il est sûr de sa réponse   (他确信自己的答案。)"],
  ["sur", "[syʁ]", "在……上面", "Le livre est sur la table   (书在桌子上。)"],
  ["sûre", "[syʁ]", "确信的（阴性单数）", "Elle est sûre de sa décision   (她对自己的决定很有把握。)"],
  ["sûrs", "[syʁ]", "确信的（阳性复数）", "Ils sont sûrs de leur choix   (他们对自己的选择很有信心。)"],
  ["sympa", "[sɛ̃  pa]", "友好的/不错的", "Ton collègue est très sympa   (你的同事很友好。)"],
  ["sympas", "[sɛ̃  pa]", "友好的/不错的（复数）", "Ces voisins sont vraiment sympas   (这些邻居真的很友好。)"],
  ["sœur", "[sœʁ]", "姐妹", "Ma sœur habite à Paris   (我姐姐住在巴黎。)"],
  ["sœurs", "[sœʁ]", "姐妹（复数）", "Elles sont deux sœurs   (她们是姐妹俩。)"],
];