var data = [
  ["t'appelles", "[ta  pɛl]", "你叫……", "Comment t'appelles-tu ? (你叫什么名字？)"],
  ["ta", "[ta]", "你的（阴性单数）", "C'est ta maison   (这是你的房子。)"],
  ["table", "[tabl]", "桌子", "La table est en bois   (这张桌子是木制的。)"],
  ["tableau", "[ta  blo]", "图画，表格", "Le tableau est accroché au mur   (图画挂在墙上。)"],
  ["tables", "[tabl]", "桌子（复数）", "Les tables sont rondes   (这些桌子是圆的。)"],
  ["tante", "[tɑ̃t]", "姑姑/阿姨", "Ma tante habite à Lyon   (我姑姑住在里昂。)"],
  ["tard", "[taʁ]", "晚，迟", "Il est déjà tard   (已经很晚了。)"],
  ["tasse", "[tas]", "杯子", "Je bois une tasse de thé   (我喝了一杯茶。)"],
  ["taxi", "[tak  si]", "出租车", "Le taxi est arrivé   (出租车到了。)"],
  ["taxis", "[tak  si]", "出租车（复数）", "Les taxis sont stationnés devant l'hôtel   (出租车停在酒店前。)"],
  ["te", "[tə]", "你", "Je te vois   (我看见你了。)"],
  ["tee-shirt", "[ti  ʃœʁt]", "T恤", "J'aime porter un tee-shirt en été   (我喜欢夏天穿T恤。)"],
  ["tee-shirts", "[ti  ʃœʁt]", "T恤（复数）", "Les tee-shirts sont en promotion   (T恤正在促销。)"],
  ["télé", "[te  le]", "电视", "Je regarde la télé ce soir   (我今晚看电视。)"],
  ["téléphone", "[te  le  fɔn]", "电话", "Le téléphone sonne   (电话响了。)"],
  ["télévision", "[te  le  vi  zjɔ̃]", "电视机", "La télévision est allumée   (电视机开着。)"],
  ["tellement", "[tɛl  mɑ̃]", "如此，非常", "Il est tellement gentil   (他非常友善。)"],
  ["temps", "[tɑ̃]", "时间", "J'ai du temps libre cet après-midi   (我今天下午有空。)"],
  ["tennis", "[te  nis]", "网球", "J'aime jouer au tennis   (我喜欢打网球。)"],
  ["tes", "[te]", "你的（复数）", "Ce sont tes livres ? (这些是你的书吗？)"],
  ["tête", "[tɛt]", "头", "J'ai mal à la tête   (我头疼。)"],
  ["ticket", "[ti  kɛ]", "票", "Voici votre ticket   (这是您的票。)"],
  ["tickets", "[ti  kɛ]", "票（复数）", "Les tickets sont disponibles à l'entrée   (票在入口处有售。)"],
  ["timbre", "[tɛ̃bʁ]", "邮票", "Je colle un timbre sur l'enveloppe   (我在信封上贴了一张邮票。)"],
  ["timide", "[ti  mid]", "害羞的", "Il est timide devant les inconnus   (他在陌生人面前很害羞。)"],
  ["timides", "[ti  mid]", "害羞的（复数）", "Les enfants sont timides aujourd'hui   (孩子们今天有点害羞。)"],
  ["toi", "[twa]", "你", "C'est pour toi   (这是给你的。)"],
  ["toilettes", "[twa  lɛt]", "卫生间", "Où sont les toilettes ? (卫生间在哪里？)"],
  ["ton", "[tɔ̃]", "你的（阳性单数）", "C'est ton livre ? (这是你的书吗？)"],
  ["tort", "[tɔʁ]", "错误，过失", "Tu as tort de ne pas l'écouter   (你不听他的话是错的。)"],
  ["tôt", "[to]", "早", "Je me lève tôt tous les jours   (我每天都早起。)"],
  ["toujours", "[tu  ʒuʁ]", "总是", "Il est toujours en retard   (他总是迟到。)"],
  ["tour", "[tuʁ]", "塔，圈", "La tour Eiffel est magnifique   (埃菲尔铁塔很壮观。)"],
  ["tourisme", "[tu  ʁizm]", "旅游", "Le tourisme est important pour l'économie   (旅游对经济很重要。)"],
  ["tourne", "[tuʁn]", "转", "Tourne à gauche   (向左转。)"],
  ["tourner", "[tuʁ  ne]", "转动，旋转", "Il faut tourner la clé pour ouvrir   (需要转动钥匙来打开。)"],
  ["tournes", "[tuʁn]", "转（第二人称单数）", "Tu tournes ici   (你在这里转弯。)"],
  ["tournez", "[tuʁ  ne]", "转（第二人称复数/敬语）", "Tournez à droite après le feu   (在红绿灯后向右转。)"],
  ["tournons", "[tuʁ  nɔ̃]", "转（第一人称复数）", "Nous tournons la page   (我们翻页。)"],
  ["tous", "[tu]", "所有的（阳性复数）", "Tous les enfants sont heureux   (所有的孩子都很开心。)"],
  ["tout", "[tu]", "所有的（阳性单数）", "Tout le monde est là   (所有人都到了。)"],
  ["tout de suite", "[tu də sɥit]", "马上，立刻", "Je reviens tout de suite   (我马上回来。)"],
  ["tout le monde", "[tu lə mɔ̃d]", "所有人", "Tout le monde est content   (所有人都很高兴。)"],
  ["toute", "[tut]", "一切，全部（阴性单数）", "Toute la journée, il a plu   (一整天都在下雨。)"],
  ["toutes", "[tut]", "所有的（阴性复数）", "Toutes les fleurs sont belles   (所有的花都很美。)"],
  ["train", "[tʁɛ̃]", "火车", "Le train arrive à l'heure   (火车准时到达。)"],
  ["trains", "[tʁɛ̃]", "火车（复数）", "Les trains sont rapides   (火车很快。)"],
  ["travail", "[tʁa  vaj]", "工作", "J'ai beaucoup de travail   (我有很多工作。)"],
  ["travaillais", "[tʁa  va  jɛ]", "工作（未完成过去式）", "Je travaillais dans une école   (我曾在一所学校工作。)"],
  ["travaille", "[tʁa  vaj]", "工作（现在时）", "Il travaille chez lui   (他在家工作。)"],
  ["travaillent", "[tʁa  vaj]", "工作（第三人称复数）", "Ils travaillent dans un bureau   (他们在办公室工作。)"],
  ["travailler", "[tʁa  va  je]", "工作（动词原形）", "J'aime travailler ici   (我喜欢在这里工作。)"],
  ["travailles", "[tʁa  vaj]", "工作（第二人称单数）", "Tu travailles tard ce soir ? (你今晚工作得很晚吗？)"],
  ["travaillez", "[tʁa  va  je]", "工作（第二人称复数/敬语）", "Vous travaillez à quelle heure ? (您几点工作？)"],
  ["travaillons", "[tʁa  va  jɔ̃]", "工作（第一人称复数）", "Nous travaillons ensemble   (我们一起工作。)"],
  ["traverse", "[tʁa  vɛʁs]", "穿过，越过", "Elle traverse la rue   (她正在过马路。)"],
  ["traverser", "[tʁa  vɛʁ  se]", "穿过（动词原形）", "Il faut traverser le pont   (需要过桥。)"],
  ["treize", "[tʁɛz]", "十三", "J'ai treize ans   (我十三岁。)"],
  ["trente", "[tʁɑ̃t]", "三十", "Il a trente minutes pour manger   (他有三十分钟吃饭。)"],
  ["très", "[tʁɛ]", "非常", "Elle est très gentille   (她非常友好。)"],
  ["triste", "[tʁist]", "悲伤的", "Il est triste aujourd'hui   (他今天很难过。)"],
  ["tristes", "[tʁist]", "悲伤的（复数）", "Les enfants sont tristes   (孩子们很难过。)"],
  ["trois", "[tʁwa]", "三", "J'ai trois frères   (我有三个兄弟。)"],
  ["troisième", "[tʁwa  zjɛm]", "第三", "C'est la troisième fois que je viens ici   (这是我第三次来这里。)"],
  ["trop", "[tʁo]", "太，过于", "Il fait trop chaud   (天气太热了。)"],
  ["trop de", "[tʁo də]", "太多", "Il y a trop de monde ici   (这里人太多了。)"],
  ["trouve", "[tʁuv]", "找到", "Elle trouve ses clés   (她找到了她的钥匙。)"],
  ["trouvent", "[tʁuv]", "找到（第三人称复数）", "Ils trouvent ça intéressant   (他们觉得这很有趣。)"],
  ["trouver", "[tʁu  ve]", "找到（动词原形）", "Je vais trouver une solution   (我会找到一个解决办法。)"],
  ["trouvons", "[tʁu  vɔ̃]", "找到（第一人称复数）", "Nous trouvons cela difficile   (我们觉得这很难。)"],
  ["tu", "[ty]", "你", "Tu viens ce soir ? (你今晚来吗？)"],
  ["tunisien", "[ty  ni  zjɛ̃]", "突尼斯的（阳性单数）", "Il est Tunisien   (他是突尼斯人。)"],
  ["tunisienne", "[ty  ni  zjɛn]", "突尼斯的（阴性单数）", "Elle est Tunisienne   (她是突尼斯人。)"],
];