var data = [
  ["va", "[va]", "去（第三人称单数）", "Elle va à l'école   (她去学校。)"],
  ["vacances", "[va  kɑ̃s]", "假期", "Nous partons en vacances   (我们去度假。)"],
  ["vaches", "[vaʃ]", "牛（复数）", "Les vaches sont dans le pré   (牛在草地上。)"],
  ["vais", "[vɛ]", "去（第一人称单数）", "Je vais au marché   (我去市场。)"],
  ["valise", "[va  liz]", "行李箱", "Cette valise est lourde   (这个行李箱很重。)"],
  ["valises", "[va  liz]", "行李箱（复数）", "Les valises sont prêtes   (行李箱已经准备好了。)"],
  ["vas", "[va]", "去（第二人称单数）", "Où vas-tu ? (你去哪儿？)"],
  ["vélo", "[ve  lo]", "自行车", "Il a un nouveau vélo   (他有一辆新自行车。)"],
  ["vend", "[vɑ̃]", "卖（第三人称单数）", "Elle vend des fleurs   (她卖花。)"],
  ["vendent", "[vɑ̃d]", "卖（第三人称复数）", "Ils vendent des fruits   (他们卖水果。)"],
  ["vendez", "[vɑ̃  de]", "卖（第二人称复数/敬语）", "Vous vendez ces livres ? (您卖这些书吗？)"],
  ["vendons", "[vɑ̃  dɔ̃]", "卖（第一人称复数）", "Nous vendons notre voiture   (我们卖掉了我们的车。)"],
  ["vendre", "[vɑ̃dʁ]", "卖（动词原形）", "Il veut vendre sa maison   (他想卖掉他的房子。)"],
  ["vendredi", "[vɑ̃  dʁə  di]", "星期五", "Nous avons un rendez-vous vendredi   (我们星期五有约会。)"],
  ["vends", "[vɑ̃]", "卖（第一/二人称单数）", "Je vends mes vêtements   (我卖我的衣服。)"],
  ["venez", "[və  ne]", "来（第二人称复数/敬语）", "Venez vite ! (快来！)"],
  ["venir", "[və  niʁ]", "来（动词原形）", "Tu veux venir avec nous ? (你想跟我们一起吗？)"],
  ["venons", "[və  nɔ̃]", "来（第一人称复数）", "Nous venons de Paris   (我们来自巴黎。)"],
  ["vent", "[vɑ̃]", "风", "Le vent souffle fort   (风吹得很大。)"],
  ["vérifier", "[ve  ʁi  fje]", "核对", "Pouvez-vous vérifier ce document ? (您能核对一下这个文件吗？)"],
  ["verre", "[vɛʁ]", "玻璃杯", "Un verre d'eau, s'il vous plaît   (请给我一杯水。)"],
  ["Versailles", "[vɛʁ  sɑj]", "凡尔赛（地名）", "Versailles est magnifique   (凡尔赛很壮观。)"],
  ["veste", "[vɛst]", "外套", "Cette veste est trop petite   (这件外套太小了。)"],
  ["vêtements", "[vɛt  mɑ̃]", "衣服（复数）", "J'ai acheté de nouveaux vêtements   (我买了新衣服。)"],
  ["veulent", "[vœl]", "想要（第三人称复数）", "Ils veulent partir tôt   (他们想早点离开。)"],
  ["veut", "[vø]", "想要（第三人称单数）", "Elle veut un gâteau   (她想要一个蛋糕。)"],
  ["veux", "[vø]", "想要（第一/二人称单数）", "Je veux un café   (我想要一杯咖啡。)"],
  ["vie", "[vi]", "生命，生活", "La vie est belle   (生活是美好的。)"],
  ["vieille", "[vjɛj]", "老的（阴性单数）", "C'est une vieille maison   (这是一座老房子。)"],
  ["vieilles", "[vjɛj]", "老的（阴性复数）", "Les vieilles photos sont dans la boîte   (老照片在盒子里。)"],
  ["viennent", "[vjɛn]", "来（第三人称复数）", "Ils viennent de rentrer   (他们刚刚回来。)"],
  ["viens", "[vjɛ̃]", "来（第一/二人称单数）", "Je viens avec toi   (我跟你一起去。)"],
  ["vient", "[vjɛ̃]", "来（第三人称单数）", "Elle vient demain   (她明天来。)"],
  ["vies", "[vi]", "生命（复数）", "Leurs vies sont très différentes   (他们的生活截然不同。)"],
  ["vieux", "[vjø]", "老的（阳性单数/复数）", "C'est un vieux livre   (这是一本旧书。)"],
  ["village", "[vi  laʒ]", "村庄", "Le village est entouré de montagnes   (村庄被群山环绕。)"],
  ["villages", "[vi  laʒ]", "村庄（复数）", "Les villages français sont charmants   (法国的村庄很迷人。)"],
  ["ville", "[vil]", "城市", "Paris est une grande ville   (巴黎是一座大城市。)"],
  ["vingt", "[vɛ̃]", "二十", "Ils ont vingt ans   (他们二十岁。)"],
  ["violon", "[vjo  lɔ̃]", "小提琴", "Il joue du violon   (他拉小提琴。)"],
  ["visage", "[vi  zaʒ]", "脸", "Elle a un joli visage   (她有一张漂亮的脸。)"],
  ["visite", "[vi  zit]", "访问（第一/三人称单数）", "Je visite un musée   (我参观一个博物馆。)"],
  ["visitent", "[vi  zit]", "访问（第三人称复数）", "Ils visitent la ville   (他们参观了这座城市。)"],
  ["visiter", "[vi  zi  te]", "访问（动词原形）", "Nous voulons visiter ce château   (我们想参观这座城堡。)"],
  ["visites", "[vi  zit]", "访问（第二人称单数）", "Tu visites souvent tes amis ? (你经常看望你的朋友吗？)"],
  ["visitez", "[vi  zi  te]", "访问（第二人称复数）", "Vous visitez toujours de beaux endroits   (您总是参观美丽的地方。)"],
  ["visitons", "[vi  zi  tɔ̃]", "访问（第一人称复数）", "Nous visitons Paris cet été   (我们今年夏天访问巴黎。)"],
  ["vite", "[vit]", "快速地", "Parlez plus vite, s'il vous plaît   (请说快一点。)"],
  ["vocabulaire", "[vɔ  ka  bylɛʁ]", "词汇", "Son vocabulaire est très riche   (他的词汇量非常丰富。)"],
  ["voici", "[vwa  si]", "这是", "Voici ton livre   (这是你的书。)"],
  ["voient", "[vwa]", "看见（第三人称复数）", "Ils voient les étoiles   (他们看见了星星。)"],
  ["voilà", "[vwa  la]", "那是", "Voilà la réponse   (那就是答案。)"],
  ["voir", "[vwaʁ]", "看见（动词原形）", "J'aime voir des films   (我喜欢看电影。)"],
  ["vois", "[vwa]", "看见（第一/二人称单数）", "Je vois un oiseau   (我看见一只鸟。)"],
  ["voit", "[vwa]", "看见（第三人称单数）", "Elle voit un bateau   (她看见一艘船。)"],
  ["voiture", "[vwa  tyʁ]", "汽车", "Ma voiture est rouge   (我的车是红色的。)"],
  ["voitures", "[vwa  tyʁ]", "汽车（复数）", "Les voitures sont garées ici   (汽车停在这里。)"],
  ["vol", "[vɔl]", "飞行；航班", "Le vol part à 10 heures   (航班10点出发。)"],
  ["vont", "[vɔ̃]", "去（第三人称复数）", "Ils vont au parc   (他们去公园。)"],
  ["vos", "[vo]", "你们的（复数）", "Vos livres sont sur la table   (你们的书在桌子上。)"],
  ["votre", "[votʁ]", "你们的（单数）", "Voici votre clé   (这是你们的钥匙。)"],
  ["voudrais", "[vudʁɛ]", "想要（条件式）", "Je voudrais un café   (我想要一杯咖啡。)"],
  ["voudrions", "[vudʁijɔ̃]", "想要（第一人称复数条件式）", "Nous voudrions partir tôt   (我们想早一点走。)"],
  ["voulais", "[vulɛ]", "想要（未完成过去式）", "Je voulais te voir   (我想见你。)"],
  ["voulait", "[vulɛ]", "想要（第三人称单数未完成过去式）", "Il voulait être médecin   (他想成为一名医生。)"],
  ["voulez", "[vule]", "想要（第二人称复数）", "Que voulez-vous manger ? (您想吃什么？)"],
  ["vouloir", "[vulwaʁ]", "想要（动词原形）", "Elle ne sait pas quoi vouloir   (她不知道想要什么。)"],
  ["voulons", "[vulɔ̃]", "想要（第一人称复数）", "Nous voulons apprendre le français   (我们想学法语。)"],
  ["vous", "[vu]", "你们；您", "Vous êtes prêts ? (你们准备好了吗？)"],
  ["vous appelez", "[vu a  pə  le]", "你们的名字是", "Comment vous appelez-vous ? (您叫什么名字？)"],
  ["voyage", "[vwa  jaʒ]", "旅行（第一/三人称单数）", "Je voyage souvent   (我经常旅行。)"],
  ["voyagent", "[vwa  jaʒ]", "旅行（第三人称复数）", "Ils voyagent en Europe   (他们在欧洲旅行。)"],
  ["voyageons", "[vwa  ja  ʒɔ̃]", "旅行（第一人称复数）", "Nous voyageons ensemble   (我们一起旅行。)"],
  ["voyager", "[vwa  jaʒe]", "旅行（动词原形）", "J'aime voyager seul   (我喜欢独自旅行。)"],
  ["voyages", "[vwa  jaʒ]", "旅行（第二人称单数）", "Tu voyages souvent en train ? (你经常坐火车旅行吗？)"],
  ["voyagez", "[vwa  ja  ʒe]", "旅行（第二人称复数）", "Vous voyagez où cet été ? (您今年夏天去哪里旅行？)"],
  ["voyez", "[vwa  je]", "看见（第二人称复数）", "Vous voyez la différence ? (您看见区别了吗？)"],
  ["voyons", "[vwa  jɔ̃]", "看见（第一人称复数）", "Nous voyons la mer d'ici   (我们从这里可以看见大海。)"],
  ["vraiment", "[vʁɛ  mɑ̃]", "真正地", "C'est vraiment incroyable   (这真的令人难以置信。)"],
];